# 01 Insurance Claims Corpus Builder

**Project:** Insurance Fraud Detection Assistant

**Notebook:** `01-insurance-claims-corpus-builder.ipynb`

In [15]:
# ====================================
# Notebook 01
# Insurance Claims Corpus Builder
# ====================================

import pandas as pd
import numpy as np

from faker import Faker

import random

In [16]:
fake = Faker()

random.seed(42)
np.random.seed(42)

In [17]:
mechanic_shops = [
    "Rapid Auto Repair",
    "Elite Collision Center",
    "Metro Auto Works",
    "Prime Vehicle Repair",
    "Trusted Auto Garage",
]

In [18]:
clinics = [
    "Care First Clinic",
    "Advanced Spine Center",
    "Metro Injury Clinic",
    "Health Plus Medical",
    "Wellness Recovery Center",
]

In [19]:
lawyers = [
    "Anderson Legal",
    "Justice Partners",
    "Smith & Associates",
    "Premier Injury Law",
    "Accident Recovery Group",
]

In [20]:
normal_claim_statements = [
    "I was driving through an intersection when another vehicle struck my car.",
    "A vehicle rear-ended me while I was waiting at a traffic signal.",
    "The driver failed to yield and collided with my vehicle.",
    "I was traveling within the speed limit when the accident occurred.",
    "The vehicle changed lanes unexpectedly and hit my car.",
]

In [21]:
police_reports = [
    "Police determined the claimant was not at fault.",
    "Witnesses confirmed another driver caused the accident.",
    "Traffic camera footage supports claimant statement.",
    "Police observed damage consistent with reported collision.",
    "Accident report indicates claimant followed traffic rules.",
]

In [22]:
def create_claim(claim_id):

    return {
        "claim_id": claim_id,
        "claimant_name": fake.name(),
        "vehicle_vin": fake.bothify(text="???###########"),
        "mechanic_shop": random.choice(mechanic_shops),
        "clinic_name": random.choice(clinics),
        "lawyer": random.choice(lawyers),
        "claimant_statement": random.choice(normal_claim_statements),
        "police_report": random.choice(police_reports),
        "adjuster_notes": fake.sentence(),
        "medical_bill": random.randint(500, 25000),
        "fraud_label": 0,
    }

In [23]:
claims = []

In [24]:
for i in range(1, 16):

    claims.append(create_claim(f"CLM{i:03}"))

In [25]:
claims_df = pd.DataFrame(claims)

In [43]:
claims_df.head(11)

,claim_id,claimant_name,vehicle_vin,mechanic_shop,clinic_name,lawyer,claimant_statement,police_report,adjuster_notes,medical_bill,fraud_label
0,CLM001,Wendy Holland,FqH15433919443,Rapid Auto Repair,Care First Clinic,Smith & Associates,A vehicle rear-ended me while I was waiting at...,Witnesses confirmed another driver caused the ...,Section international though many movement.,5072,0
1,CLM002,Douglas Lara,acF49501195178,Rapid Auto Repair,Wellness Recovery Center,Anderson Legal,The vehicle changed lanes unexpectedly and hit...,Police observed damage consistent with reporte...,Budget Mrs part spend middle threat smile incr...,1541,0
2,CLM003,Chloe Murphy,xeQ24677572737,Rapid Auto Repair,Care First Clinic,Justice Partners,I was stopped at a red light when another vehi...,Accident report indicates claimant followed tr...,Similar never box line.,20226,1
3,CLM004,Jodi Reynolds MD,sPL40843321198,Rapid Auto Repair,Wellness Recovery Center,Justice Partners,The vehicle changed lanes unexpectedly and hit...,Police observed damage consistent with reporte...,Section season nor political bank.,7723,0
4,CLM005,Elizabeth Patel,mmr35740163797,Prime Vehicle Repair,Wellness Recovery Center,Smith & Associates,I was driving through an intersection when ano...,Witnesses confirmed another driver caused the ...,Kind compare across audience society.,23376,0
5,CLM006,Kevin Paul,cMw46708542594,Prime Vehicle Repair,Metro Injury Clinic,Smith & Associates,\n\nMy neck and lower back experienced severe ...,Witnesses confirmed another driver caused the ...,Employee raise financial.,11529,1
6,CLM007,Lisa Rich,lEk94627470017,Rapid Auto Repair,Care First Clinic,Premier Injury Law,I was driving through an intersection when ano...,Traffic camera footage supports claimant state...,Say moment election certain stuff staff bed.,11770,0
7,CLM008,Pamela Hayes,yfD17615912160,Trusted Auto Garage,Metro Injury Clinic,Anderson Legal,I was traveling within the speed limit when th...,Accident report indicates claimant followed tr...,Brother they take positive apply relate.,4590,0
8,CLM009,Kendra Reyes,SVZ01756439163,Prime Vehicle Repair,Care First Clinic,Accident Recovery Group,The driver failed to yield and collided with m...,Accident report indicates claimant followed tr...,Treatment change building interesting scene.,12350,0
9,CLM010,Julia Wilson,UsI18443206019,Trusted Auto Garage,Advanced Spine Center,Anderson Legal,I was driving through an intersection when ano...,Witnesses confirmed another driver caused the ...,Way two modern another defense middle.,9982,0
10,CLM011,Patrick Harvey,leO61992562839,Rapid Auto Repair,Advanced Spine Center,Anderson Legal,\n\nMy neck and lower back experienced severe ...,Traffic camera footage supports claimant state...,Fire audience exist evening story to develop.,15357,1

In [29]:
claims_df.loc[2, "claimant_statement"] = (
    "I was stopped at a red light when another vehicle hit me."
)

In [31]:
claims_df.loc[2, "fraud_label"] = 1

In [33]:
template_text = """

My neck and lower back experienced severe pain immediately after impact.

The collision caused significant emotional distress and loss of mobility.

I continue to experience discomfort.
"""

In [34]:
claims_df.loc[5, "claimant_statement"] = template_text

In [36]:
claims_df.loc[10, "claimant_statement"] = template_text

In [37]:
claims_df.loc[[5, 10], "fraud_label"] = 1

In [41]:
ring_shop = "Rapid Auto Repair"

ring_clinic = "Metro Injury Clinic"

ring_lawyer = "Premier Injury Law"

In [42]:
ring_claims = [7, 8, 9]

In [44]:
for idx in ring_claims:

    claims_df.loc[idx, "mechanic_shop"] = ring_shop

    claims_df.loc[idx, "clinic_name"] = ring_clinic

    claims_df.loc[idx, "lawyer"] = ring_lawyer

    claims_df.loc[idx, "fraud_label"] = 1

In [45]:
claims_df[claims_df["fraud_label"] == 1]

,claim_id,claimant_name,vehicle_vin,mechanic_shop,clinic_name,lawyer,claimant_statement,police_report,adjuster_notes,medical_bill,fraud_label
2,CLM003,Chloe Murphy,xeQ24677572737,Rapid Auto Repair,Care First Clinic,Justice Partners,I was stopped at a red light when another vehi...,Accident report indicates claimant followed tr...,Similar never box line.,20226,1
5,CLM006,Kevin Paul,cMw46708542594,Prime Vehicle Repair,Metro Injury Clinic,Smith & Associates,\n\nMy neck and lower back experienced severe ...,Witnesses confirmed another driver caused the ...,Employee raise financial.,11529,1
7,CLM008,Pamela Hayes,yfD17615912160,Rapid Auto Repair,Metro Injury Clinic,Premier Injury Law,I was traveling within the speed limit when th...,Accident report indicates claimant followed tr...,Brother they take positive apply relate.,4590,1
8,CLM009,Kendra Reyes,SVZ01756439163,Rapid Auto Repair,Metro Injury Clinic,Premier Injury Law,The driver failed to yield and collided with m...,Accident report indicates claimant followed tr...,Treatment change building interesting scene.,12350,1
9,CLM010,Julia Wilson,UsI18443206019,Rapid Auto Repair,Metro Injury Clinic,Premier Injury Law,I was driving through an intersection when ano...,Witnesses confirmed another driver caused the ...,Way two modern another defense middle.,9982,1
10,CLM011,Patrick Harvey,leO61992562839,Rapid Auto Repair,Advanced Spine Center,Anderson Legal,\n\nMy neck and lower back experienced severe ...,Traffic camera footage supports claimant state...,Fire audience exist evening story to develop.,15357,1

In [46]:
claims_df.shape

(15, 11)

In [47]:
claims_df["fraud_label"].value_counts()

fraud_label
0    9
1    6
Name: count, dtype: int64

In [48]:
claims_df.groupby("fraud_label").size()

fraud_label
0    9
1    6
dtype: int64

In [50]:
claims_df.to_csv("../data/insurance_claims.csv", index=False)

In [51]:
insurance_df = pd.read_csv("../data/insurance_claims.csv")

In [52]:
insurance_df.head()

,claim_id,claimant_name,vehicle_vin,mechanic_shop,clinic_name,lawyer,claimant_statement,police_report,adjuster_notes,medical_bill,fraud_label
0,CLM001,Wendy Holland,FqH15433919443,Rapid Auto Repair,Care First Clinic,Smith & Associates,A vehicle rear-ended me while I was waiting at...,Witnesses confirmed another driver caused the ...,Section international though many movement.,5072,0
1,CLM002,Douglas Lara,acF49501195178,Rapid Auto Repair,Wellness Recovery Center,Anderson Legal,The vehicle changed lanes unexpectedly and hit...,Police observed damage consistent with reporte...,Budget Mrs part spend middle threat smile incr...,1541,0
2,CLM003,Chloe Murphy,xeQ24677572737,Rapid Auto Repair,Care First Clinic,Justice Partners,I was stopped at a red light when another vehi...,Accident report indicates claimant followed tr...,Similar never box line.,20226,1
3,CLM004,Jodi Reynolds MD,sPL40843321198,Rapid Auto Repair,Wellness Recovery Center,Justice Partners,The vehicle changed lanes unexpectedly and hit...,Police observed damage consistent with reporte...,Section season nor political bank.,7723,0
4,CLM005,Elizabeth Patel,mmr35740163797,Prime Vehicle Repair,Wellness Recovery Center,Smith & Associates,I was driving through an intersection when ano...,Witnesses confirmed another driver caused the ...,Kind compare across audience society.,23376,0

In [53]:
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   claim_id            15 non-null     object
 1   claimant_name       15 non-null     object
 2   vehicle_vin         15 non-null     object
 3   mechanic_shop       15 non-null     object
 4   clinic_name         15 non-null     object
 5   lawyer              15 non-null     object
 6   claimant_statement  15 non-null     object
 7   police_report       15 non-null     object
 8   adjuster_notes      15 non-null     object
 9   medical_bill        15 non-null     int64
 10  fraud_label         15 non-null     int64
dtypes: int64(2), object(9)
memory usage: 1.4+ KB