In [3]:
# ==========================================================
# Notebook 01: Building Enterprise Corpus
# ==========================================================

import random
import uuid

import numpy as np
import pandas as pd

In [4]:
# -----------------------------------
# Configuration
# -----------------------------------

RANDOM_SEED = 42

np.random.seed(RANDOM_SEED)

random.seed(RANDOM_SEED)

In [5]:
sources = ["Slack", "Confluence", "Jira"]

departments = ["Engineering", "HR", "Finance", "Legal"]

In [6]:
slack_messages = [
    {
        "source": "Slack",
        "title": "Phoenix Deployment Discussion",
        "content": (
            "The Phoenix-2026 deployment "
            "is scheduled for next Friday. "
            "Database migration will happen "
            "during the maintenance window."
        ),
        "author": "Alice",
    },
    {
        "source": "Slack",
        "title": "Model Training Update",
        "content": (
            "The semantic search model "
            "has been retrained using "
            "new support ticket data."
        ),
        "author": "Bob",
    },
]

slack_messages

[{'source': 'Slack',
  'title': 'Phoenix Deployment Discussion',
  'content': 'The Phoenix-2026 deployment is scheduled for next Friday. Database migration will happen during the maintenance window.',
  'author': 'Alice'},
 {'source': 'Slack',
  'title': 'Model Training Update',
  'content': 'The semantic search model has been retrained using new support ticket data.',
  'author': 'Bob'}]

In [7]:
confluence_pages = [
    {
        "source": "Confluence",
        "title": "Phoenix Architecture Wiki",
        "content": (
            "Project Phoenix-2026 follows "
            "a microservice architecture "
            "using Kubernetes and FastAPI."
        ),
        "author": "Charlie",
    },
    {
        "source": "Confluence",
        "title": "Enterprise Search Design",
        "content": (
            "Hybrid search combines BM25 "
            "keyword retrieval and "
            "semantic vector retrieval."
        ),
        "author": "Diana",
    },
]

confluence_pages

[{'source': 'Confluence',
  'title': 'Phoenix Architecture Wiki',
  'content': 'Project Phoenix-2026 follows a microservice architecture using Kubernetes and FastAPI.',
  'author': 'Charlie'},
 {'source': 'Confluence',
  'title': 'Enterprise Search Design',
  'content': 'Hybrid search combines BM25 keyword retrieval and semantic vector retrieval.',
  'author': 'Diana'}]

In [8]:
jira_tickets = [
    {
        "source": "Jira",
        "title": "PHX-245 Database Migration",
        "content": (
            "Complete PostgreSQL migration " "before Phoenix production launch."
        ),
        "author": "Eric",
    },
    {
        "source": "Jira",
        "title": "SEC-104 ACL Enhancement",
        "content": (
            "Implement metadata-based "
            "access control filtering "
            "for enterprise search."
        ),
        "author": "Fiona",
    },
]

jira_tickets

[{'source': 'Jira',
  'title': 'PHX-245 Database Migration',
  'content': 'Complete PostgreSQL migration before Phoenix production launch.',
  'author': 'Eric'},
 {'source': 'Jira',
  'title': 'SEC-104 ACL Enhancement',
  'content': 'Implement metadata-based access control filtering for enterprise search.',
  'author': 'Fiona'}]

In [9]:
enterprise_records = slack_messages + confluence_pages + jira_tickets

In [10]:
enterprise_records

[{'source': 'Slack',
  'title': 'Phoenix Deployment Discussion',
  'content': 'The Phoenix-2026 deployment is scheduled for next Friday. Database migration will happen during the maintenance window.',
  'author': 'Alice'},
 {'source': 'Slack',
  'title': 'Model Training Update',
  'content': 'The semantic search model has been retrained using new support ticket data.',
  'author': 'Bob'},
 {'source': 'Confluence',
  'title': 'Phoenix Architecture Wiki',
  'content': 'Project Phoenix-2026 follows a microservice architecture using Kubernetes and FastAPI.',
  'author': 'Charlie'},
 {'source': 'Confluence',
  'title': 'Enterprise Search Design',
  'content': 'Hybrid search combines BM25 keyword retrieval and semantic vector retrieval.',
  'author': 'Diana'},
 {'source': 'Jira',
  'title': 'PHX-245 Database Migration',
  'content': 'Complete PostgreSQL migration before Phoenix production launch.',
  'author': 'Eric'},
 {'source': 'Jira',
  'title': 'SEC-104 ACL Enhancement',
  'content': 'Implement metadata-based access control filtering for enterprise search.',
  'author': 'Fiona'}]

In [11]:
for idx, record in enumerate(enterprise_records, start=1):

    record["doc_id"] = f"DOC{idx:04d}"

    record["department"] = random.choice(departments)

    record["created_date"] = f"2026-01-{10 + idx}"

    record["tags"] = random.sample(
        [
            "enterprise-search",
            "phoenix",
            "database",
            "acl",
            "fastapi",
            "semantic-search",
            "kubernetes",
        ],
        k=2,
    )

In [12]:
enterprise_df = pd.DataFrame(enterprise_records)

enterprise_df

,source,title,content,author,doc_id,department,created_date,tags
0,Slack,Phoenix Deployment Discussion,The Phoenix-2026 deployment is scheduled for n...,Alice,DOC0001,Engineering,2026-01-11,"[enterprise-search, semantic-search]"
1,Slack,Model Training Update,The semantic search model has been retrained u...,Bob,DOC0002,Finance,2026-01-12,"[phoenix, kubernetes]"
2,Confluence,Phoenix Architecture Wiki,Project Phoenix-2026 follows a microservice ar...,Charlie,DOC0003,HR,2026-01-13,"[semantic-search, enterprise-search]"
3,Confluence,Enterprise Search Design,Hybrid search combines BM25 keyword retrieval ...,Diana,DOC0004,Engineering,2026-01-14,"[fastapi, acl]"
4,Jira,PHX-245 Database Migration,Complete PostgreSQL migration before Phoenix p...,Eric,DOC0005,Engineering,2026-01-15,"[enterprise-search, kubernetes]"
5,Jira,SEC-104 ACL Enhancement,Implement metadata-based access control filter...,Fiona,DOC0006,HR,2026-01-16,"[phoenix, fastapi]"

In [13]:
print("Total Documents:", len(enterprise_df))

print("\nSources:")

print(enterprise_df["source"].value_counts())

print("\nDepartments:")

print(enterprise_df["department"].value_counts())

Total Documents: 6

Sources:
source
Slack         2
Confluence    2
Jira          2
Name: count, dtype: int64

Departments:
department
Engineering    3
HR             2
Finance        1
Name: count, dtype: int64

In [14]:
source_summary = (
    enterprise_df.groupby("source").size().reset_index(name="document_count")
)

source_summary

       source  document_count
0  Confluence               2
1        Jira               2
2       Slack               2

In [15]:
OUTPUT_PATH = "data/processed/"

import os

os.makedirs(OUTPUT_PATH, exist_ok=True)

enterprise_df.to_csv(os.path.join(OUTPUT_PATH, "enterprise_corpus.csv"), index=False)

print("Enterprise corpus saved!")

Enterprise corpus saved!

In [16]:
loaded_df = pd.read_csv("data/processed/enterprise_corpus.csv")

loaded_df.head()

,source,title,content,author,doc_id,department,created_date,tags
0,Slack,Phoenix Deployment Discussion,The Phoenix-2026 deployment is scheduled for n...,Alice,DOC0001,Engineering,2026-01-11,"['enterprise-search', 'semantic-search']"
1,Slack,Model Training Update,The semantic search model has been retrained u...,Bob,DOC0002,Finance,2026-01-12,"['phoenix', 'kubernetes']"
2,Confluence,Phoenix Architecture Wiki,Project Phoenix-2026 follows a microservice ar...,Charlie,DOC0003,HR,2026-01-13,"['semantic-search', 'enterprise-search']"
3,Confluence,Enterprise Search Design,Hybrid search combines BM25 keyword retrieval ...,Diana,DOC0004,Engineering,2026-01-14,"['fastapi', 'acl']"
4,Jira,PHX-245 Database Migration,Complete PostgreSQL migration before Phoenix p...,Eric,DOC0005,Engineering,2026-01-15,"['enterprise-search', 'kubernetes']"

In [17]:
enterprise_df[(enterprise_df["department"] == "Engineering")]

,source,title,content,author,doc_id,department,created_date,tags
0,Slack,Phoenix Deployment Discussion,The Phoenix-2026 deployment is scheduled for n...,Alice,DOC0001,Engineering,2026-01-11,"[enterprise-search, semantic-search]"
3,Confluence,Enterprise Search Design,Hybrid search combines BM25 keyword retrieval ...,Diana,DOC0004,Engineering,2026-01-14,"[fastapi, acl]"
4,Jira,PHX-245 Database Migration,Complete PostgreSQL migration before Phoenix p...,Eric,DOC0005,Engineering,2026-01-15,"[enterprise-search, kubernetes]"