In [2]:
# ==========================================
# Notebook 01
# Recommendation Data Sandbox
# ==========================================

import pandas as pd
import numpy as np

In [3]:
items = [
    {
        "item_id": 1,
        "title": "The Early Days of Stripe",
        "category": "Startup",
        "description": """
        Story of how Stripe scaled into
        one of the world's largest
        fintech companies.
        """,
    },
    {
        "item_id": 2,
        "title": "Building SpaceX",
        "category": "Startup",
        "description": """
        Deep dive into SpaceX,
        rocket engineering,
        and company growth.
        """,
    },
    {
        "item_id": 3,
        "title": "AI for Healthcare",
        "category": "Artificial Intelligence",
        "description": """
        Applications of AI
        in healthcare,
        diagnostics,
        and medical imaging.
        """,
    },
    {
        "item_id": 4,
        "title": "The Psychology of Habits",
        "category": "Wellness",
        "description": """
        Habit formation,
        behavior change,
        and productivity.
        """,
    },
    {
        "item_id": 5,
        "title": "Cloud Computing Fundamentals",
        "category": "Technology",
        "description": """
        Introduction to cloud platforms,
        distributed systems,
        and scalability.
        """,
    },
    {
        "item_id": 6,
        "title": "Modern Data Engineering",
        "category": "Data Engineering",
        "description": """
        Data pipelines,
        ETL systems,
        data warehouses,
        and analytics.
        """,
    },
    {
        "item_id": 7,
        "title": "Machine Learning in Finance",
        "category": "Machine Learning",
        "description": """
        Predictive analytics,
        financial forecasting,
        and AI applications.
        """,
    },
    {
        "item_id": 8,
        "title": "Startup Fundraising Guide",
        "category": "Startup",
        "description": """
        Venture capital,
        seed funding,
        and startup growth.
        """,
    },
    {
        "item_id": 9,
        "title": "Nutrition Science",
        "category": "Health",
        "description": """
        Diet,
        nutrition,
        and long-term wellness.
        """,
    },
    {
        "item_id": 10,
        "title": "Large Language Models",
        "category": "Artificial Intelligence",
        "description": """
        Transformers,
        LLMs,
        generative AI,
        and prompt engineering.
        """,
    },
]

In [4]:
items_df = pd.DataFrame(items)

items_df

,item_id,title,category,description
0,1,The Early Days of Stripe,Startup,\n Story of how Stripe scaled into\n ...
1,2,Building SpaceX,Startup,"\n Deep dive into SpaceX,\n rock..."
2,3,AI for Healthcare,Artificial Intelligence,\n Applications of AI\n in healt...
3,4,The Psychology of Habits,Wellness,"\n Habit formation,\n behavior c..."
4,5,Cloud Computing Fundamentals,Technology,"\n Introduction to cloud platforms,\n ..."
5,6,Modern Data Engineering,Data Engineering,"\n Data pipelines,\n ETL systems..."
6,7,Machine Learning in Finance,Machine Learning,"\n Predictive analytics,\n finan..."
7,8,Startup Fundraising Guide,Startup,"\n Venture capital,\n seed fundi..."
8,9,Nutrition Science,Health,"\n Diet,\n nutrition,\n a..."
9,10,Large Language Models,Artificial Intelligence,"\n Transformers,\n LLMs,\n ..."

In [5]:
print("Total Items:", len(items_df))

print()

items_df.columns

Total Items: 10

Index(['item_id', 'title', 'category', 'description'], dtype='object')

In [6]:
items_df["category"].value_counts()

category
Startup                    3
Artificial Intelligence    2
Wellness                   1
Technology                 1
Data Engineering           1
Machine Learning           1
Health                     1
Name: count, dtype: int64

In [7]:
users = [
    {"user_id": 101, "persona": "Tech Enthusiast"},
    {"user_id": 102, "persona": "Startup Founder"},
    {"user_id": 103, "persona": "Health Reader"},
    {"user_id": 104, "persona": "AI Researcher"},
    {"user_id": 105, "persona": "Data Engineer"},
]

In [8]:
users_df = pd.DataFrame(users)

users_df

   user_id          persona
0      101  Tech Enthusiast
1      102  Startup Founder
2      103    Health Reader
3      104    AI Researcher
4      105    Data Engineer

In [9]:
interactions = [
    [101, 1, 5],
    [101, 2, 5],
    [101, 5, 4],
    [102, 1, 5],
    [102, 8, 5],
    [102, 2, 4],
    [103, 4, 5],
    [103, 9, 5],
    [104, 3, 5],
    [104, 10, 5],
    [104, 7, 4],
    [105, 5, 5],
    [105, 6, 5],
    [105, 7, 4],
]

In [10]:
interactions_df = pd.DataFrame(interactions, columns=["user_id", "item_id", "rating"])

interactions_df

    user_id  item_id  rating
0       101        1       5
1       101        2       5
2       101        5       4
3       102        1       5
4       102        8       5
5       102        2       4
6       103        4       5
7       103        9       5
8       104        3       5
9       104       10       5
10      104        7       4
11      105        5       5
12      105        6       5
13      105        7       4

In [11]:
print("Interactions:", len(interactions_df))

print()

print("Unique Users:", interactions_df["user_id"].nunique())

print()

print("Unique Items:", interactions_df["item_id"].nunique())

Interactions: 14

Unique Users: 5

Unique Items: 10

In [12]:
interactions_df["rating"].value_counts()

rating
5    10
4     4
Name: count, dtype: int64

In [13]:
user_history = pd.merge(interactions_df, items_df, on="item_id")

user_history

,user_id,item_id,rating,title,category,description
0,101,1,5,The Early Days of Stripe,Startup,\n Story of how Stripe scaled into\n ...
1,101,2,5,Building SpaceX,Startup,"\n Deep dive into SpaceX,\n rock..."
2,101,5,4,Cloud Computing Fundamentals,Technology,"\n Introduction to cloud platforms,\n ..."
3,102,1,5,The Early Days of Stripe,Startup,\n Story of how Stripe scaled into\n ...
4,102,8,5,Startup Fundraising Guide,Startup,"\n Venture capital,\n seed fundi..."
5,102,2,4,Building SpaceX,Startup,"\n Deep dive into SpaceX,\n rock..."
6,103,4,5,The Psychology of Habits,Wellness,"\n Habit formation,\n behavior c..."
7,103,9,5,Nutrition Science,Health,"\n Diet,\n nutrition,\n a..."
8,104,3,5,AI for Healthcare,Artificial Intelligence,\n Applications of AI\n in healt...
9,104,10,5,Large Language Models,Artificial Intelligence,"\n Transformers,\n LLMs,\n ..."
10,104,7,4,Machine Learning in Finance,Machine Learning,"\n Predictive analytics,\n finan..."
11,105,5,5,Cloud Computing Fundamentals,Technology,"\n Introduction to cloud platforms,\n ..."
12,105,6,5,Modern Data Engineering,Data Engineering,"\n Data pipelines,\n ETL systems..."
13,105,7,4,Machine Learning in Finance,Machine Learning,"\n Predictive analytics,\n finan..."

In [14]:
user_history[user_history["user_id"] == 101]

,user_id,item_id,rating,title,category,description
0,101,1,5,The Early Days of Stripe,Startup,\n Story of how Stripe scaled into\n ...
1,101,2,5,Building SpaceX,Startup,"\n Deep dive into SpaceX,\n rock..."
2,101,5,4,Cloud Computing Fundamentals,Technology,"\n Introduction to cloud platforms,\n ..."

In [15]:
user_history[user_history["user_id"] == 102]

,user_id,item_id,rating,title,category,description
3,102,1,5,The Early Days of Stripe,Startup,\n Story of how Stripe scaled into\n ...
4,102,8,5,Startup Fundraising Guide,Startup,"\n Venture capital,\n seed fundi..."
5,102,2,4,Building SpaceX,Startup,"\n Deep dive into SpaceX,\n rock..."

In [16]:
user_history[user_history["user_id"] == 104]

,user_id,item_id,rating,title,category,description
8,104,3,5,AI for Healthcare,Artificial Intelligence,\n Applications of AI\n in healt...
9,104,10,5,Large Language Models,Artificial Intelligence,"\n Transformers,\n LLMs,\n ..."
10,104,7,4,Machine Learning in Finance,Machine Learning,"\n Predictive analytics,\n finan..."

In [17]:
interaction_matrix = interactions_df.pivot_table(
    index="user_id", columns="item_id", values="rating"
)

In [18]:
interaction_matrix

item_id   1    2    3    4    5    6    7    8    9    10
user_id
101      5.0  5.0  NaN  NaN  4.0  NaN  NaN  NaN  NaN  NaN
102      5.0  4.0  NaN  NaN  NaN  NaN  NaN  5.0  NaN  NaN
103      NaN  NaN  NaN  5.0  NaN  NaN  NaN  NaN  5.0  NaN
104      NaN  NaN  5.0  NaN  NaN  NaN  4.0  NaN  NaN  5.0
105      NaN  NaN  NaN  NaN  5.0  5.0  4.0  NaN  NaN  NaN

In [19]:
interaction_matrix.shape

(5, 10)

In [20]:
total_cells = interaction_matrix.shape[0] * interaction_matrix.shape[1]

filled_cells = interaction_matrix.count().sum()

sparsity = 1 - (filled_cells / total_cells)

print("Sparsity:", round(sparsity, 4))

Sparsity: 0.72

In [21]:
items_df.to_csv("../data/items.csv", index=False)

In [22]:
interactions_df.to_csv("../data/user_interactions.csv", index=False)

In [23]:
interaction_matrix.to_csv("../data/interaction_matrix.csv")

In [24]:
saved_items = pd.read_csv("../data/items.csv")

saved_items.head()

,item_id,title,category,description
0,1,The Early Days of Stripe,Startup,\n Story of how Stripe scaled into\n ...
1,2,Building SpaceX,Startup,"\n Deep dive into SpaceX,\n rock..."
2,3,AI for Healthcare,Artificial Intelligence,\n Applications of AI\n in healt...
3,4,The Psychology of Habits,Wellness,"\n Habit formation,\n behavior c..."
4,5,Cloud Computing Fundamentals,Technology,"\n Introduction to cloud platforms,\n ..."

In [25]:
users_df.to_csv("../data/users.csv", index=False)