In [2]:
# ==========================================
# Notebook 03
# Content Profiling Engine
# ==========================================

import pandas as pd
import numpy as np

In [3]:
items_df = pd.read_csv("../data/items.csv")

items_df.head()

,item_id,title,category,description
0,1,The Early Days of Stripe,Startup,\n Story of how Stripe scaled into\n ...
1,2,Building SpaceX,Startup,"\n Deep dive into SpaceX,\n rock..."
2,3,AI for Healthcare,Artificial Intelligence,\n Applications of AI\n in healt...
3,4,The Psychology of Habits,Wellness,"\n Habit formation,\n behavior c..."
4,5,Cloud Computing Fundamentals,Technology,"\n Introduction to cloud platforms,\n ..."

In [4]:
print("Total Items:", len(items_df))

print()

items_df.columns

Total Items: 10

Index(['item_id', 'title', 'category', 'description'], dtype='object')

In [5]:
items_df.iloc[0]

item_id                                                        1
title                                   The Early Days of Stripe
category                                                 Startup
description    \n        Story of how Stripe scaled into\n   ...
Name: 0, dtype: object

In [6]:
tag_mapping = {
    "Startup": "startup fintech founders entrepreneurship venture-capital",
    "Artificial Intelligence": "ai machine-learning llm deep-learning transformers",
    "Technology": "cloud computing distributed-systems scalability",
    "Data Engineering": "etl pipelines analytics warehousing",
    "Machine Learning": "machine-learning predictive-modeling ai",
    "Health": "health nutrition wellness",
    "Wellness": "habits productivity self-improvement",
}

In [7]:
items_df["tags"] = items_df["category"].map(tag_mapping)

items_df.head()

,item_id,title,category,description,tags
0,1,The Early Days of Stripe,Startup,\n Story of how Stripe scaled into\n ...,startup fintech founders entrepreneurship vent...
1,2,Building SpaceX,Startup,"\n Deep dive into SpaceX,\n rock...",startup fintech founders entrepreneurship vent...
2,3,AI for Healthcare,Artificial Intelligence,\n Applications of AI\n in healt...,ai machine-learning llm deep-learning transfor...
3,4,The Psychology of Habits,Wellness,"\n Habit formation,\n behavior c...",habits productivity self-improvement
4,5,Cloud Computing Fundamentals,Technology,"\n Introduction to cloud platforms,\n ...",cloud computing distributed-systems scalability

In [8]:
items_df["content_profile"] = (
    "Title: "
    + items_df["title"]
    + " Category: "
    + items_df["category"]
    + " Tags: "
    + items_df["tags"]
    + " Description: "
    + items_df["description"]
)

In [9]:
items_df[["item_id", "content_profile"]].head()

   item_id                                    content_profile
0        1  Title: The Early Days of Stripe Category: Star...
1        2  Title: Building SpaceX Category: Startup Tags:...
2        3  Title: AI for Healthcare Category: Artificial ...
3        4  Title: The Psychology of Habits Category: Well...
4        5  Title: Cloud Computing Fundamentals Category: ...

In [10]:
print(items_df.iloc[0]["content_profile"])

Title: The Early Days of Stripe Category: Startup Tags: startup fintech founders entrepreneurship venture-capital Description:
        Story of how Stripe scaled into
        one of the world's largest
        fintech companies.

In [11]:
items_df["profile_length"] = items_df["content_profile"].apply(len)

In [12]:
items_df[["title", "profile_length"]]

                          title  profile_length
0      The Early Days of Stripe             238
1               Building SpaceX             214
2             AI for Healthcare             238
3      The Psychology of Habits             192
4  Cloud Computing Fundamentals             228
5       Modern Data Engineering             215
6   Machine Learning in Finance             220
7     Startup Fundraising Guide             212
8             Nutrition Science             161
9         Large Language Models             233

In [13]:
items_df["profile_length"].describe()

count     10.000000
mean     215.100000
std       23.642946
min      161.000000
25%      212.500000
50%      217.500000
75%      231.750000
max      238.000000
Name: profile_length, dtype: float64

In [14]:
items_df.sort_values(by="profile_length", ascending=False)[["title", "profile_length"]]

                          title  profile_length
0      The Early Days of Stripe             238
2             AI for Healthcare             238
9         Large Language Models             233
4  Cloud Computing Fundamentals             228
6   Machine Learning in Finance             220
5       Modern Data Engineering             215
1               Building SpaceX             214
7     Startup Fundraising Guide             212
3      The Psychology of Habits             192
8             Nutrition Science             161

In [15]:
items_df.groupby("category")["profile_length"].mean()

category
Artificial Intelligence    235.500000
Data Engineering           215.000000
Health                     161.000000
Machine Learning           220.000000
Startup                    221.333333
Technology                 228.000000
Wellness                   192.000000
Name: profile_length, dtype: float64

In [16]:
recommendation_corpus = items_df["content_profile"].tolist()

In [17]:
len(recommendation_corpus)

10

In [18]:
profile_df = items_df[["item_id", "title", "category", "tags", "content_profile"]]

profile_df.head()

,item_id,title,category,tags,content_profile
0,1,The Early Days of Stripe,Startup,startup fintech founders entrepreneurship vent...,Title: The Early Days of Stripe Category: Star...
1,2,Building SpaceX,Startup,startup fintech founders entrepreneurship vent...,Title: Building SpaceX Category: Startup Tags:...
2,3,AI for Healthcare,Artificial Intelligence,ai machine-learning llm deep-learning transfor...,Title: AI for Healthcare Category: Artificial ...
3,4,The Psychology of Habits,Wellness,habits productivity self-improvement,Title: The Psychology of Habits Category: Well...
4,5,Cloud Computing Fundamentals,Technology,cloud computing distributed-systems scalability,Title: Cloud Computing Fundamentals Category: ...

In [19]:
profile_df.isnull().sum()

item_id            0
title              0
category           0
tags               0
content_profile    0
dtype: int64

In [20]:
profile_df["content_profile"].duplicated().sum()

0

In [21]:
profile_df[profile_df["content_profile"].str.contains("fintech", case=False)]

,item_id,title,category,tags,content_profile
0,1,The Early Days of Stripe,Startup,startup fintech founders entrepreneurship vent...,Title: The Early Days of Stripe Category: Star...
1,2,Building SpaceX,Startup,startup fintech founders entrepreneurship vent...,Title: Building SpaceX Category: Startup Tags:...
7,8,Startup Fundraising Guide,Startup,startup fintech founders entrepreneurship vent...,Title: Startup Fundraising Guide Category: Sta...

In [22]:
profile_df[profile_df["content_profile"].str.contains("transformers", case=False)]

,item_id,title,category,tags,content_profile
2,3,AI for Healthcare,Artificial Intelligence,ai machine-learning llm deep-learning transfor...,Title: AI for Healthcare Category: Artificial ...
9,10,Large Language Models,Artificial Intelligence,ai machine-learning llm deep-learning transfor...,Title: Large Language Models Category: Artific...

In [23]:
profile_df[profile_df["content_profile"].str.contains("startup", case=False)]

,item_id,title,category,tags,content_profile
0,1,The Early Days of Stripe,Startup,startup fintech founders entrepreneurship vent...,Title: The Early Days of Stripe Category: Star...
1,2,Building SpaceX,Startup,startup fintech founders entrepreneurship vent...,Title: Building SpaceX Category: Startup Tags:...
7,8,Startup Fundraising Guide,Startup,startup fintech founders entrepreneurship vent...,Title: Startup Fundraising Guide Category: Sta...

In [24]:
profile_df.to_csv("../data/item_profiles.csv", index=False)

In [25]:
corpus_df = pd.DataFrame({"content": recommendation_corpus})

corpus_df.to_csv("../data/recommendation_corpus.csv", index=False)

In [26]:
saved_profiles = pd.read_csv("../data/item_profiles.csv")

saved_profiles.head()

,item_id,title,category,tags,content_profile
0,1,The Early Days of Stripe,Startup,startup fintech founders entrepreneurship vent...,Title: The Early Days of Stripe Category: Star...
1,2,Building SpaceX,Startup,startup fintech founders entrepreneurship vent...,Title: Building SpaceX Category: Startup Tags:...
2,3,AI for Healthcare,Artificial Intelligence,ai machine-learning llm deep-learning transfor...,Title: AI for Healthcare Category: Artificial ...
3,4,The Psychology of Habits,Wellness,habits productivity self-improvement,Title: The Psychology of Habits Category: Well...
4,5,Cloud Computing Fundamentals,Technology,cloud computing distributed-systems scalability,Title: Cloud Computing Fundamentals Category: ...