In [1]:
# ==========================================================
# Notebook 02: Resume Section Extraction
# ==========================================================

import re
import pandas as pd

In [2]:
resumes_df = pd.read_csv("processed/parsed_resumes.csv")

resumes_df.head()

,file_name,raw_text,text_length
0,10554236.pdf,ACCOUNTANT Summary Financial Accountant specia...,24153
1,10674770.pdf,STAFF ACCOUNTANT Summary Highly analytical and...,7488
2,11163645.pdf,ACCOUNTANT Professional Summary To obtain a po...,4736
3,11759079.pdf,SENIOR ACCOUNTANT Experience Company Name June...,5917
4,12065211.pdf,SENIOR ACCOUNTANT Professional Summary Senior ...,5561

In [3]:
sample_resume = resumes_df.loc[0, "raw_text"]

print(sample_resume)

ACCOUNTANT Summary Financial Accountant specializing in financial planning, reporting and analysis within the Department of Defense. Highlights Account reconciliations Results-oriented Accounting operations professional Financial reporting Analysis of financial systems Critical thinking ERP (Enterprise Resource Planning) software. Excellent facilitator Accomplishments Served on a tiger team which identified and resolved General Ledger postings in DEAMS totaling $360B in accounting adjustments. This allowed for the first successful fiscal year-end close for 2012. In collaboration with DFAS Europe, developed an automated tool that identified duplicate obligations. This tool allowed HQ USAFE to deobligate over $5M in duplicate obligations. Experience Company Name July 2011 to November 2012 Accountant City , State Enterprise Resource Planning Office (ERO) In this position as an Accountant assigned to the Defense Enterprise Accounting and Management System (DEAMS) ERO I was responsible for identifying and resolving issues affecting the DEAMS General Ledger. I worked with teammates from the Procure to Pay, Orders to Cash, and Budget to Report areas to resolve daily challenges encountered with the deployment of DEAMS to additional customers and when system change requests were promoted to production. I supported the testing of scripts, patches, and system change requests ensuring any anomalies were identified to the DEAMS Functional Management Office for action by the DEAMS Program Management Office and/or the System Integrator. In addition, I served on a tiger team designed to identify and resolve General Ledger posting differences and supported the development of $360B in accounting adjustments allowing for the first successful fiscal year-end close in 2012. These actions also allowed for the reconciliation and closure of fiscal year 2010 and 2011 accounting adjustments ensuring that all DEAMS fiscal year-end requirements were completed. These actions were recognized as critical to the successful review report issued by the Air Force Operational Test and Evaluation Center (AFOTEC) resulting in the Air Force receiving the authority to continue with the deployment of DEAMS. Company Name April 2010 to June 2011 Resource Advisor City , State In this position as Resource Advisor for the 1st Air Communications Operation Squadron (1ACOS) I was responsible for providing financial advice and decision support to the Commander. I was responsible for coordinating a $4.6M budget between four funding sources. I coordinated with USAFE Directorate of Intelligence (USAFE/A2), USAFE Directorate of Air and Space Operations (USAFE/A3), USAFE Directorate of Communications (USAFE/A6) and the 435th Air Ground Operations Wing to ensure 1ACOS meets its mission requirements. I consistently managed three separate timelines for providing budget/unfunded requirements, providing documentation and various reports in the required format for each organization. I discussed the outcome of the Group and Directorate budget meetings providing feedback the same day to the Flight Chiefs and CC any issue which affects 1ACOS directly. I monitored the Defense Travel System (DTS) daily and identify orders and authorizations needing approval and provided notification to the appropriate Reviewing Officials and Approvers. Utilizing DTS and the General Accounting and Finance System I reviewed status reports to identify anomalies in obligations and have identified those orders which require correction prior to payment. I provided Government Purchase Card (GPC) status reports the same day they are requested and in addition, communicated with the appropriate cardholders when changes were required to support their program. I identified cardholder training requirements and monitored these requirements to ensure all required training was completed in support of this mission critical program. I developed guidance for the GPC cardholders on procedures for requesting training for the squadron and in addition I provided answers to cardholder questions on unique or non-standard issues/concerns. Assumed the role of the Billing Official during my final rating period and completed a self inspection of the program for the Management Control Program, zero findings. During yearly audit by 700th CONS received zero findings. Company Name July 2008 to April 2010 Staff Accountant City , State In my position as the Staff Accountant for HQ USAFE I was responsible for providing accounting and financial oversight and advice to customers throughout the Command in support of the USAFE Comptroller. I was responsible for performing ongoing analysis of financial programs to identify negative trends and weaknesses, ensured specific weaknesses were corrected, and determined whether systemic or repeat issues were identified and adequately addressed. I was required to apply a comprehensive knowledge of analysis/reporting requirements and data produced to resolve these issues. In collaboration with DFAS Europe, developed an automated tool that identifies duplicate obligations by comparing records in the accounting system to the contracting system and provided notification to the funds manager for review and resolution. This tool eliminated hours of manual research and results allowed HQ USAFE to deobligate over $5M in duplicate obligations. I was responsible for establishing various performance metrics which ensured effective and efficient use of USAFE financial resources. I supported the USAFE/FMA Financial metrics program by collaborating with DFAS Limestone in the development of an automated tool that provided senior leaders with visibility to any USAFE unit that is not in compliance with the established rules and regulations related to the GPC. This tool provides management reports that are used to populate the monthly metric charts which are briefed by the USAFE/FMA. This tool provided the capability for USAFE/FMA to collaborate with USAFE Contracting and develop/deploy joint guidance that supports the established Air Force Instruction mandating card suspension for card holders who are not in compliance with required reservation of funds in the entitlement system in support of the GPC. I identified and resolved a problem with five GPC accounts that had been rejecting during the automated interface process each month. My research revealed that these accounts were rejecting for invalid paying station and required manual intervention by both Wing and DFAS personnel. This not only created rework, it delayed the payment of the invoices. I partnered with DFAS Denver, corrected the records in the Access On-Line accounts eliminating the error condition. I identified a method to deliver one-on-one training in support of the USAFE deployment of the Open Document Analysis (ODA) tool in FMSuite. By utilizing Defense Connect Online I provided training remotely, virtually eliminating the need to expend funds on Temporary Duty (TDY) travel. The results of this training produced results that went well above expectations and were noted by the ODA Program Management Office. Company Name January 2007 to July 2009 Chief, Reports Branch. Accounts Maintenance and Control City , State In my position as Chief of the Reports Branch in Accounts Maintenance & Control (AM&C) I was responsible for ensuring the development and standardization of various managerial and system reports. I was responsible for the completeness and accuracy of weekly, monthly, quarterly, semi-annual, and annual reports. My branch monitored errors in the General Accounting and Finance System (GAFS/BQ) and ensured corrective actions were accomplished. I also ensured fund balances were reconciled and reports were verified prior to release to base activities and higher headquarters. Limestone reorganized under the High Performing Organization (HPO) in January 2007 and at that time I was reassigned to AM&C, a Directorate which previously did not exist. My challenge during that time was to staff my branch, implement an aggressive training schedule, and ensure the continuity of financial reporting was maintained. As we transitioned into the HPO we continued defining the missions and functions for AM&C for the entire network. I participated in biweekly conference calls with Standards and Compliance in an effort to define missions and functions for AM&C. Worked with management in determining FTEs needed for the branch. I was responsible for developing meaningful performance standards for my employees since this branch and its functions did not previously exist. Limestone POC for an initiative to eliminate suspense accounts throughout the agency. Identified suspense accounts not initially targeted, formulated strategies to eliminate accounts or requested waivers, and participated in plans to modify processes using suspense accounts, such as the interfund suspense account. These actions provided initial progress towards meeting the Department of Treasury's mandate to discontinue suspense accounts by February 2009. Worked with staff to reduce reconciliations from $6.9 million in February 2007 to $1.1 million in August, accomplished this despite loss in experienced personnel and realigning resources to support critical initiatives in Accounts Payable. I orchestrated the transition of reporting requirements for the Transportation Financial Management System (TFMS) workload from DFAS Omaha to Limestone. After transition to Limestone encouraged staff responsible for these reports to streamline the processes. Staff automated a completely manual, time consuming process, thus eliminating potential key stroke errors and manually validating numerous spreadsheets and listings. Contributor to Federal Managers Financial Integrity Act (FMFIA) Compliance Review and establishment of assessable units. Identified inconsistencies in information provided by staff on foreign currency fluctuation adjustments. Persisted in getting higher level review of regulatory and policy guidance. Report of foreign currency fluctuation is now consistently accurate. Company Name February 2000 to January 2007 Chief, Accounts Payable Branch City , State As Chief Of Accounts Payable I was responsible for the overall management of a branch consisting of over 120 employees. My four first line supervisors were responsible for establishing priorities, schedules, and work assignments ensuring changes in workload are accounted for to minimize the impact on normal office operations. We consistently reviewed these areas and made necessary personnel moves based on shifting priorities. This was extremely important during the DFAS Denver directed database consolidations and with the assumption of the Air National Guard workload. Workload increased rapidly while staffing increased gradually, which dictated frequent priority changes and personnel moves. I also worked closely with the Major Commands supported by DFAS Limestone strengthening our partnership when workload spikes negatively impacted our customers. In December 2004, our overaged invoice percentage was nearing 25% and we had a backlog of vendor pay documents exceeding 30,000. By working with the DFAS Command Client Executives and the Major Command Comptrollers, I was instrumental in forming a strategy that included soliciting Air Force personnel assistance in document processing, identification of "must pay now" bills, and the formation of special action response teams dedicated to responding to our customer's most urgent requirements. As a result of these efforts, in a three month period, we were able to reduce our overaged invoice percentage by 19% and our backlog of documents to no documents over 20 days old thereby minimizing the adverse impact on customer funds. I was responsible for providing personnel feedback sessions quarterly and prepared supervisory appraisals of employees' performance and potential for advancement. Partnering with the management staff and employees, I was instrumental in establishing Employee Performance Plans that linked employee performance to established DFAS Strategies and Balance Scorecard goals. In this position as a supervisory accountant I was responsible for performing ongoing analysis of the Vendor Pay workflow and production to identify negative trends and weaknesses, ensure specific weaknesses have been corrected, and determine whether systemic or repeat issues have been identified and adequately addressed. I was required to apply a comprehensive knowledge of analysis/reporting requirements, work processes, vendor pay system structures, and data produced to resolve these issues. Utilizing my expertise with Louis II data retrieval software, I produced ad-hoc data queries for in-house and external use by our customers. These retrievals were designed to reduce the man- hours necessary to perform complex finance and accounting functions by DFAS and Air Force personnel. I was responsible for the budget resources necessary to operate the branch. In this capacity, I prepared budget over execution justifications, plan and monitor overtime costs, and control supply purchases to ensure the most cost efficient operation possible. I was required to respond to inquiries from various sources, which include, but are not limited to, vendors, DFAS management, accounting liaison offices, resource advisors, and other DFAS field sites. These inquiries required my ability to relay technical aspects of systems deficiencies to customers who are not familiar with our operation. I participated in video teleconferences, conference calls, and briefings designed to address customer and DFAS management requirements. I was called upon to explain, in laymen's terms, DFAS policy and procedures with regards to delays in payment due to various reasons. I responded to various audit reports and studies; ensuring senior management and audit personnel, understand particular situations within the Vendor Pay business process that result in these findings. Company Name February 1999 to February 2000 Chief, Recon and Reports Branch City , State In my position as Chief, Vendor Pay Reports and Recon Branch, I exercised supervision (either directly or indirectly) over 22 employees primarily in the "525" series in grades ranging from GS-5 through GS-8. This responsibility also included supervision of the German local national workers assigned to my duty section. I was responsible for planning, directing, and supervising the activities of the work force in the review, interpretation, processing, and reconciliation of vendor pay and accounting data and the production of timely and accurate financial statement report requirements. I participated in the development of branch policies continually reviewing and evaluating the organizational operations, work distribution, and procedures. I coordinated the activities of the assigned functions with those of other organizations to obtain the most effective correlation of financial data. Directed and provided technical guidance to subordinates in the assigned area. Assured the timeliness and accuracy of assigned workload. Planned, organized, directed, coordinated, and reviewed the work of subordinate's sections ensuring the mission and functions of the division were carried out. I managed and realigned resources, conducted program analyses, and made decisions in accordance with unit cost principles, outputs, targets, and changing budgetary constraints. I participated in long range planning, goal setting, and evaluating the subordinate staff. Interpreted and clarified branch policies and resolved operational problems. Ensured efficient utilization and professional development of my staff. I was expected to provide reasonable assurance that operations were conducted in compliance with applicable laws and that funds, property, and other assets were safeguarded against waste, loss, unauthorized use, or misappropriation. I ensured continuing and affirmative application and support of DoD and DFAS policy concerning the equal opportunity and affirmative action programs. Ensured personnel management within organizational entity under my supervision was accomplished without regard to race, color, religion, sex, age, national origin, or handicap. I kept abreast of developments, policy issuance, and other similar material in the equal opportunity field and fully supported the DoD and DFAS Equal Opportunity Program. I was responsible and accountable for the safety and health of my subordinates. I ensured personnel were trained to work safely. I enforced safety and health rules, corrected unsafe or unhealthy acts and unsafe or unhealthy mechanical or physical conditions, investigated mishaps and tool other actions necessary to ensure the safety and health of my employees. Company Name June 1995 to February 1999 Chief, Accounts Payable Branch City , State I was responsible for establishing priorities, schedules, and work assignments ensuring changes in workload are accounted for to minimize the impact on normal office operations. This was important during the DFAS Denver directed workload realighment to the Field Sites servicing our customers by Major Command. Workload increased which dictated frequent priority changes and personnel moves. I also worked closely with the Major Commands supported by DFAS Limestone strengthening our partnership when workload spikes negatively impacted our customers. I was responsible for providing personnel feedback sessions quarterly and preparedsupervisory appraisals of employees' performance and potential for advancement. As a supervisory accountant I was responsible for performing ongoing analysis of the Vendor Pay workflow and production. I identified negative trends and weaknesses, ensured specific weaknesses were corrected, and determine whether systemic or repeat issues were identified and adequately addressed. I was required to apply a comprehensive knowledge of analysis/reporting requirements, work processes, vendor pay system structures, and data produced to resolve these issues. Utilizing my knowledge with Louis II data retrieval software, I produced ad-hoc data queries for in-house and external use by our customers. These retrievals are all designed to reduce the man- hours necessary to perform complex finance and accounting functions by DFAS and Air Force personnel. I was responsible for the budget resources necessary to operate the branch. In this capacity, I prepared budget over execution justifications, plan and monitor overtime costs, and control supply purchases to ensure the most cost efficient operation possible. I was required to respond to inquiries from various sources, which include, but are not limited to, vendors, DFAS management, accounting liaison offices, resource advisors, and other DFAS field sites. These inquiries require my ability to relay technical aspects of systems deficiencies to customers who are not familiar with our operation. I participated in video teleconferences, conference calls, and briefings designed to address customer and DFAS management requirements. I was often called upon to explain, in laymen's terms, DFAS policy and procedures with regards to delays in payment due to various reasons. I was required to respond to various audit reports and studies; ensuring senior management and audit personnel, understand particular situations within the Vendor Pay business process that result in these findings. I was hand selected by the Field Site Director and Vendor Pay Site Manager to represent DFAS Limestone on a team comprised of representatives from all DFAS Denver field sites to provide training to our Air Force base level Resource Advisors. During a five week period, I provided "Boot Camp" training to over 400 base level personnel ensuring resource advisors were familiar with the DFAS structure and mission requirements related to funds management. Company Name June 1994 to June 1995 Accountant, Network Assistant Team City , State As a member of the Ne

In [4]:
SECTION_PATTERNS = {
    "skills": [
        "skills",
        "technical skills",
        "core competencies",
        "technical expertise",
    ],
    "experience": [
        "experience",
        "work experience",
        "professional experience",
        "employment history",
    ],
    "education": ["education", "academic background", "academic qualifications"],
    "certifications": ["certifications", "certificates", "licenses"],
}

In [5]:
def normalize_text(text):

    text = text.lower()

    text = re.sub(r"\s+", " ", text)

    return text

In [6]:
normalized_resume = normalize_text(sample_resume)

print(normalized_resume[:1000])

accountant summary financial accountant specializing in financial planning, reporting and analysis within the department of defense. highlights account reconciliations results-oriented accounting operations professional financial reporting analysis of financial systems critical thinking erp (enterprise resource planning) software. excellent facilitator accomplishments served on a tiger team which identified and resolved general ledger postings in deams totaling $360b in accounting adjustments. this allowed for the first successful fiscal year-end close for 2012. in collaboration with dfas europe, developed an automated tool that identified duplicate obligations. this tool allowed hq usafe to deobligate over $5m in duplicate obligations. experience company name july 2011 to november 2012 accountant city , state enterprise resource planning office (ero) in this position as an accountant assigned to the defense enterprise accounting and management system (deams) ero i was responsible for

In [7]:
def find_section_position(text, section_keywords):

    positions = []

    for keyword in section_keywords:

        match = re.search(rf"\b{re.escape(keyword)}\b", text)

        if match:

            positions.append(match.start())

    if len(positions) == 0:
        return None

    return min(positions)

In [8]:
def extract_resume_sections(resume_text, section_patterns):

    text = normalize_text(resume_text)

    section_positions = {}

    # Find all section locations
    for section_name, keywords in section_patterns.items():

        position = find_section_position(text, keywords)

        if position is not None:

            section_positions[section_name] = position

    # Sort by appearance
    ordered_sections = sorted(section_positions.items(), key=lambda x: x[1])

    extracted_sections = {}

    for idx, (section_name, start_pos) in enumerate(ordered_sections):

        if idx + 1 < len(ordered_sections):

            end_pos = ordered_sections[idx + 1][1]

        else:

            end_pos = len(text)

        extracted_sections[section_name] = text[start_pos:end_pos].strip()

    return extracted_sections

In [9]:
sections = extract_resume_sections(sample_resume, SECTION_PATTERNS)

sections

{'experience': 'experience company name july 2011 to november 2012 accountant city , state enterprise resource planning office (ero) in this position as an accountant assigned to the defense enterprise accounting and management system (deams) ero i was responsible for identifying and resolving issues affecting the deams general ledger. i worked with teammates from the procure to pay, orders to cash, and budget to report areas to resolve daily challenges encountered with the deployment of deams to additional customers and when system change requests were promoted to production. i supported the testing of scripts, patches, and system change requests ensuring any anomalies were identified to the deams functional management office for action by the deams program management office and/or the system integrator. in addition, i served on a tiger team designed to identify and resolve general ledger posting differences and supported the development of $360b in accounting adjustments allowing for the first successful fiscal year-end close in 2012. these actions also allowed for the reconciliation and closure of fiscal year 2010 and 2011 accounting adjustments ensuring that all deams fiscal year-end requirements were completed. these actions were recognized as critical to the successful review report issued by the air force operational test and evaluation center (afotec) resulting in the air force receiving the authority to continue with the deployment of deams. company name april 2010 to june 2011 resource advisor city , state in this position as resource advisor for the 1st air communications operation squadron (1acos) i was responsible for providing financial advice and decision support to the commander. i was responsible for coordinating a $4.6m budget between four funding sources. i coordinated with usafe directorate of intelligence (usafe/a2), usafe directorate of air and space operations (usafe/a3), usafe directorate of communications (usafe/a6) and the 435th air ground operations wing to ensure 1acos meets its mission requirements. i consistently managed three separate timelines for providing budget/unfunded requirements, providing documentation and various reports in the required format for each organization. i discussed the outcome of the group and directorate budget meetings providing feedback the same day to the flight chiefs and cc any issue which affects 1acos directly. i monitored the defense travel system (dts) daily and identify orders and authorizations needing approval and provided notification to the appropriate reviewing officials and approvers. utilizing dts and the general accounting and finance system i reviewed status reports to identify anomalies in obligations and have identified those orders which require correction prior to payment. i provided government purchase card (gpc) status reports the same day they are requested and in addition, communicated with the appropriate cardholders when changes were required to support their program. i identified cardholder training requirements and monitored these requirements to ensure all required training was completed in support of this mission critical program. i developed guidance for the gpc cardholders on procedures for requesting training for the squadron and in addition i provided answers to cardholder questions on unique or non-standard issues/concerns. assumed the role of the billing official during my final rating period and completed a self inspection of the program for the management control program, zero findings. during yearly audit by 700th cons received zero findings. company name july 2008 to april 2010 staff accountant city , state in my position as the staff accountant for hq usafe i was responsible for providing accounting and financial oversight and advice to customers throughout the command in support of the usafe comptroller. i was responsible for performing ongoing analysis of financial programs to identify negative trends and weaknesses, ensured specific weaknesses were corrected, and determined whether systemic or repeat issues were identified and adequately addressed. i was required to apply a comprehensive knowledge of analysis/reporting requirements and data produced to resolve these issues. in collaboration with dfas europe, developed an automated tool that identifies duplicate obligations by comparing records in the accounting system to the contracting system and provided notification to the funds manager for review and resolution. this tool eliminated hours of manual research and results allowed hq usafe to deobligate over $5m in duplicate obligations. i was responsible for establishing various performance metrics which ensured effective and efficient use of usafe financial resources. i supported the usafe/fma financial metrics program by collaborating with dfas limestone in the development of an automated tool that provided senior leaders with visibility to any usafe unit that is not in compliance with the established rules and regulations related to the gpc. this tool provides management reports that are used to populate the monthly metric charts which are briefed by the usafe/fma. this tool provided the capability for usafe/fma to collaborate with usafe contracting and develop/deploy joint guidance that supports the established air force instruction mandating card suspension for card holders who are not in compliance with required reservation of funds in the entitlement system in support of the gpc. i identified and resolved a problem with five gpc accounts that had been rejecting during the automated interface process each month. my research revealed that these accounts were rejecting for invalid paying station and required manual intervention by both wing and dfas personnel. this not only created rework, it delayed the payment of the invoices. i partnered with dfas denver, corrected the records in the access on-line accounts eliminating the error condition. i identified a method to deliver one-on-one training in support of the usafe deployment of the open document analysis (oda) tool in fmsuite. by utilizing defense connect online i provided training remotely, virtually eliminating the need to expend funds on temporary duty (tdy) travel. the results of this training produced results that went well above expectations and were noted by the oda program management office. company name january 2007 to july 2009 chief, reports branch. accounts maintenance and control city , state in my position as chief of the reports branch in accounts maintenance & control (am&c) i was responsible for ensuring the development and standardization of various managerial and system reports. i was responsible for the completeness and accuracy of weekly, monthly, quarterly, semi-annual, and annual reports. my branch monitored errors in the general accounting and finance system (gafs/bq) and ensured corrective actions were accomplished. i also ensured fund balances were reconciled and reports were verified prior to release to base activities and higher headquarters. limestone reorganized under the high performing organization (hpo) in january 2007 and at that time i was reassigned to am&c, a directorate which previously did not exist. my challenge during that time was to staff my branch, implement an aggressive training schedule, and ensure the continuity of financial reporting was maintained. as we transitioned into the hpo we continued defining the missions and functions for am&c for the entire network. i participated in biweekly conference calls with standards and compliance in an effort to define missions and functions for am&c. worked with management in determining ftes needed for the branch. i was responsible for developing meaningful performance standards for my employees since this branch and its functions did not previously exist. limestone poc for an initiative to eliminate suspense accounts throughout the agency. identified suspense accounts not initially targeted, formulated strategies to eliminate accounts or requested waivers, and participated in plans to modify processes using suspense accounts, such as the interfund suspense account. these actions provided initial progress towards meeting the department of treasury\'s mandate to discontinue suspense accounts by february 2009. worked with staff to reduce reconciliations from $6.9 million in february 2007 to $1.1 million in august, accomplished this despite loss in experienced personnel and realigning resources to support critical initiatives in accounts payable. i orchestrated the transition of reporting requirements for the transportation financial management system (tfms) workload from dfas omaha to limestone. after transition to limestone encouraged staff responsible for these reports to streamline the processes. staff automated a completely manual, time consuming process, thus eliminating potential key stroke errors and manually validating numerous spreadsheets and listings. contributor to federal managers financial integrity act (fmfia) compliance review and establishment of assessable units. identified inconsistencies in information provided by staff on foreign currency fluctuation adjustments. persisted in getting higher level review of regulatory and policy guidance. report of foreign currency fluctuation is now consistently accurate. company name february 2000 to january 2007 chief, accounts payable branch city , state as chief of accounts payable i was responsible for the overall management of a branch consisting of over 120 employees. my four first line supervisors were responsible for establishing priorities, schedules, and work assignments ensuring changes in workload are accounted for to minimize the impact on normal office operations. we consistently reviewed these areas and made necessary personnel moves based on shifting priorities. this was extremely important during the dfas denver directed database consolidations and with the assumption of the air national guard workload. workload increased rapidly while staffing increased gradually, which dictated frequent priority changes and personnel moves. i also worked closely with the major commands supported by dfas limestone strengthening our partnership when workload spikes negatively impacted our customers. in december 2004, our overaged invoice percentage was nearing 25% and we had a backlog of vendor pay documents exceeding 30,000. by working with the dfas command client executives and the major command comptrollers, i was instrumental in forming a strategy that included soliciting air force personnel assistance in document processing, identification of "must pay now" bills, and the formation of special action response teams dedicated to responding to our customer\'s most urgent requirements. as a result of these efforts, in a three month period, we were able to reduce our overaged invoice percentage by 19% and our backlog of documents to no documents over 20 days old thereby minimizing the adverse impact on customer funds. i was responsible for providing personnel feedback sessions quarterly and prepared supervisory appraisals of employees\' performance and potential for advancement. partnering with the management staff and employees, i was instrumental in establishing employee performance plans that linked employee performance to established dfas strategies and balance scorecard goals. in this position as a supervisory accountant i was responsible for performing ongoing analysis of the vendor pay workflow and production to identify negative trends and weaknesses, ensure specific weaknesses have been corrected, and determine whether systemic or repeat issues have been identified and adequately addressed. i was required to apply a comprehensive knowledge of analysis/reporting requirements, work processes, vendor pay system structures, and data produced to resolve these issues. utilizing my expertise with louis ii data retrieval software, i produced ad-hoc data queries for in-house and external use by our customers. these retrievals were designed to reduce the man- hours necessary to perform complex finance and accounting functions by dfas and air force personnel. i was responsible for the budget resources necessary to operate the branch. in this capacity, i prepared budget over execution justifications, plan and monitor overtime costs, and control supply purchases to ensure the most cost efficient operation possible. i was required to respond to inquiries from various sources, which include, but are not limited to, vendors, dfas management, accounting liaison offices, resource advisors, and other dfas field sites. these inquiries required my ability to relay technical aspects of systems deficiencies to customers who are not familiar with our operation. i participated in video teleconferences, conference calls, and briefings designed to address customer and dfas management requirements. i was called upon to explain, in laymen\'s terms, dfas policy and procedures with regards to delays in payment due to various reasons. i responded to various audit reports and studies; ensuring senior management and audit personnel, understand particular situations within the vendor pay business process that result in these findings. company name february 1999 to february 2000 chief, recon and reports branch city , state in my position as chief, vendor pay reports and recon branch, i exercised supervision (either directly or indirectly) over 22 employees primarily in the "525" series in grades ranging from gs-5 through gs-8. this responsibility also included supervision of the german local national workers assigned to my duty section. i was responsible for planning, directing, and supervising the activities of the work force in the review, interpretation, processing, and reconciliation of vendor pay and accounting data and the production of timely and accurate financial statement report requirements. i participated in the development of branch policies continually reviewing and evaluating the organizational operations, work distribution, and procedures. i coordinated the activities of the assigned functions with those of other organizations to obtain the most effective correlation of financial data. directed and provided technical guidance to subordinates in the assigned area. assured the timeliness and accuracy of assigned workload. planned, organized, directed, coordinated, and reviewed the work of subordinate\'s sections ensuring the mission and functions of the division were carried out. i managed and realigned resources, conducted program analyses, and made decisions in accordance with unit cost principles, outputs, targets, and changing budgetary constraints. i participated in long range planning, goal setting, and evaluating the subordinate staff. interpreted and clarified branch policies and resolved operational problems. ensured efficient utilization and professional development of my staff. i was expected to provide reasonable assurance that operations were conducted in compliance with applicable laws and that funds, property, and other assets were safeguarded against waste, loss, unauthorized use, or misappropriation. i ensured continuing and affirmative application and support of dod and dfas policy concerning the equal opportunity and affirmative action programs. ensured personnel management within organizational entity under my supervision was accomplished without regard to race, color, religion, sex, age, national origin, or handicap. i kept abreast of developments, policy issuance, and other similar material in the equal opportunity field and fully supported the dod and dfas equal opportunity program. i was responsible and accountable for the safety and health of my subordinates. i ensured personnel were trained to work safely. i enforced safety and health rules, corrected unsafe or unhealthy acts and unsafe or unhealthy mechanical or physical conditions, investigated mishaps and tool other actions necessary to ensure the safety and health of my employees. company name june 1995 to february 1999 chief, accounts payable branch city , state i was responsible for establishing priorities, schedules, and work assignments ensuring changes in workload are accounted for to minimize the impact on normal office operations. this was important during the dfas denver directed workload realighment to the field sites servicing our customers by major command. workload increased which dictated frequent priority changes and personnel moves. i also worked closely with the major commands supported by dfas limestone strengthening our partnership when workload spikes negatively impacted our customers. i was responsible for providing personnel feedback sessions quarterly and preparedsupervisory appraisals of employees\' performance and potential for advancement. as a supervisory accountant i was responsible for performing ongoing analysis of the vendor pay workflow and production. i identified negative trends and weaknesses, ensured specific weaknesses were corrected, and determine whether systemic or repeat issues were identified and adequately addressed. i was required to apply a comprehensive knowledge of analysis/reporting requirements, work processes, vendor pay system structures, and data produced to resolve these issues. utilizing my knowledge with louis ii data retrieval software, i produced ad-hoc data queries for in-house and external use by our customers. these retrievals are all designed to reduce the man- hours necessary to perform complex finance and accounting functions by dfas and air force personnel. i was responsible for the budget resources necessary to operate the branch. in this capacity, i prepared budget over execution justifications, plan and monitor overtime costs, and control supply purchases to ensure the most cost efficient operation possible. i was required to respond to inquiries from various sources, which include, but are not limited to, vendors, dfas management, accounting liaison offices, resource advisors, and other dfas field sites. these inquiries require my ability to relay technical aspects of systems deficiencies to customers who are not familiar with our operation. i participated in video teleconferences, conference calls, and briefings designed to address customer and dfas management requirements. i was often called upon to explain, in laymen\'s terms, dfas policy and procedures with regards to delays in payment due to various reasons. i was required to respond to various audit reports and studies; ensuring senior management and audit personnel, understand particular situations within the vendor pay business process that result in these findings. i was hand selected by the field site director and vendor pay site manager to represent dfas limestone on a team comprised of representatives from all dfas denver field sites to provide training to our air force base level resource advisors. during a five week period, i provided "boot camp" training to over 400 base level personnel ensuring resource advisors were familiar with the dfas structure and mission requirements related to funds management. company name june 1994 to june 1995 accountant, network assistant team city , state as a member of the network assistance team, i was required to have an extensive working knowledge of dod accounting systems, theory, policy, and procedures. i was consistently called upon to develop and implement procedures consistent with dod regulations. coordinated with dfas denver and the omaha field site on the consolidation of the first geographically separated defense accounting office into dfas. in my position as a member of the network assistance team i was required, upon arrival at each base level defense accounting office (dao) to provide an in-brief. this briefing identified team members, the purpose of the visit, goals, and responsibilities. upon completion of the assignment, provided a written and oral out-brief outlining

In [10]:
print("===== SKILLS =====")

print(sections.get("skills", ""))

print("\n===== EXPERIENCE =====")

print(sections.get("experience", ""))

print("\n===== EDUCATION =====")

print(sections.get("education", ""))

===== SKILLS =====
skills accounting; general accounting; accounts payable; program management.

===== EXPERIENCE =====

In [11]:
parsed_sections = []

for _, row in resumes_df.iterrows():

    extracted = extract_resume_sections(row["raw_text"], SECTION_PATTERNS)

    parsed_sections.append(
        {
            "file_name": row["file_name"],
            "skills": extracted.get("skills", ""),
            "experience": extracted.get("experience", ""),
            "education": extracted.get("education", ""),
            "certifications": extracted.get("certifications", ""),
        }
    )

In [12]:
sections_df = pd.DataFrame(parsed_sections)

sections_df.head()

,file_name,skills,experience,education,certifications
0,10554236.pdf,skills accounting; general accounting; account...,experience company name july 2011 to november ...,education northern maine community college 199...,certifications certified defense financial man...
1,10674770.pdf,skills. highlights dba quick books mas - sage ...,experience staff accountant january 2014 to oc...,"education bachelor of science : accounting , m...",
2,11163645.pdf,skills and attributes. attributes self-motivat...,experience accountant january 2011 to november...,education computer applications specialist cer...,
3,11759079.pdf,skills by drafting over forty memorandums that...,experience company name june 2011 to current s...,"education emory university, goizueta business ...",certifications and awards fulton county casa b...
4,12065211.pdf,skills aderant/cms financial reporting excel u...,experience in full life cycle of general ledge...,education bachelor of business administration ...,"certifications certified public accountant, ne..."

In [13]:
sections_df.to_csv("processed/resume_sections.csv", index=False)

print("Section extraction completed.")

Section extraction completed.

In [14]:
def extract_skill_list(skills_text):

    skills = re.split(r"[,|•|\n]", skills_text)

    skills = [skill.strip() for skill in skills if len(skill.strip()) > 1]

    return skills

In [15]:
sample_skills = extract_skill_list(sections.get("skills", ""))

sample_skills

['skills accounting; general accounting; accounts payable; program management.']