# 01 Corporate Document Ingestion

**Project:** Enterprise Multi-Document RAG Assistant

**Notebook:** `01-corporate-document-ingestion.ipynb`

In [1]:
# Start coding here

In [2]:
# !pip install pandas
# !pip install faker
# !pip install pathlib

In [3]:
# ==================================================
# Notebook 01
# Corporate Document Ingestion
# ==================================================

import os
import json
import uuid

import pandas as pd

from pathlib import Path

In [4]:
folders = [
    "data",
    "data/hr",
    "data/finance",
    "data/engineering",
    "artifacts",
    "reports",
]

for folder in folders:

    os.makedirs(folder, exist_ok=True)

print("Folders created.")

Folders created.

In [5]:
hr_doc = """
# Employee Benefits 2026

## Health Insurance

Health insurance coverage increased by 12%.

The company expanded hospitalization benefits.

Employees can now add dependents at reduced rates.

## Dental Benefits

Dental insurance remains unchanged.

Preventive dental checkups remain fully covered.

Orthodontic coverage was extended for children.

## Remote Work Policy

Remote work allowance increased.

Employees may claim internet reimbursement.

Work-from-home equipment support continues.

Benefit | Coverage
Health Insurance | 12% Increase
Dental Insurance | No Change
Remote Work Allowance | Increased
"""

finance_doc = """
# Annual Financial Report 2026

## Revenue Performance

Revenue reached $5.2 billion.

Revenue increased across all regions.

Subscription services contributed strongly.

## Profitability

Operating margin improved to 18%.

Cost optimization reduced expenses.

Free cash flow reached record levels.

## Cloud Division

Cloud division grew by 35%.

AI products generated record profits.

Enterprise customers expanded usage.

Region | Revenue
US | 2.1B
Europe | 1.7B
Asia | 1.4B
"""

engineering_doc = """
# AI Platform Roadmap

## Search Infrastructure

Vector search infrastructure rollout.

Search latency improved significantly.

New indexing pipeline deployed.

## Retrieval Systems

Hybrid retrieval implementation.

Semantic search quality improved.

Knowledge base coverage expanded.

## Deployment Roadmap

Cross encoder deployment planned.

Enterprise RAG platform launch Q3.

Agentic workflows under evaluation.

Component | Status
Vector Search | Production
Hybrid Retrieval | Testing
Cross Encoder | Planned
"""

In [6]:
documents = {
    "data/hr/Benefits_2026.txt": hr_doc,
    "data/finance/Annual_Report_2026.txt": finance_doc,
    "data/engineering/AI_Roadmap.txt": engineering_doc,
}

for filepath, content in documents.items():

    with open(filepath, "w", encoding="utf-8") as file:

        file.write(content)

print("Documents saved.")

Documents saved.

In [7]:
for root, dirs, files in os.walk("data"):

    for file in files:

        print(os.path.join(root, file))

data\engineering\AI_Roadmap.txt
data\finance\Annual_Report_2026.txt
data\hr\Benefits_2026.txt

In [8]:
document_schema = {
    "document_id": "",
    "filename": "",
    "department": "",
    "doc_type": "",
    "created_at": "",
    "content": "",
}

document_schema

{'document_id': '',
 'filename': '',
 'department': '',
 'doc_type': '',
 'created_at': '',
 'content': ''}

In [9]:
def load_document(filepath):

    with open(filepath, "r", encoding="utf-8") as file:

        text = file.read()

    return text

In [10]:
def create_document_record(filepath):

    content = load_document(filepath)

    department = Path(filepath).parent.name

    return {
        "document_id": str(uuid.uuid4()),
        "filename": Path(filepath).name,
        "department": department,
        "doc_type": "corporate_document",
        "created_at": "2026-01-01",
        "content": content,
    }

In [11]:
records = []

for root, dirs, files in os.walk("data"):

    for file in files:

        filepath = os.path.join(root, file)

        record = create_document_record(filepath)

        records.append(record)

In [12]:
documents_df = pd.DataFrame(records)

documents_df.head()

,document_id,filename,department,doc_type,created_at,content
0,1fe99400-06e1-4964-956b-3861687e7da4,AI_Roadmap.txt,engineering,corporate_document,2026-01-01,\n# AI Platform Roadmap\n\n## Search Infrastru...
1,b638264b-b788-442e-a09d-19176466fba8,Annual_Report_2026.txt,finance,corporate_document,2026-01-01,\n# Annual Financial Report 2026\n\n## Revenue...
2,31516a79-2cf5-4080-ac66-66b338d6ebff,Benefits_2026.txt,hr,corporate_document,2026-01-01,\n# Employee Benefits 2026\n\n## Health Insura...

In [13]:
documents_df["char_count"] = documents_df["content"].apply(len)

documents_df[["filename", "department", "char_count"]]

                 filename   department  char_count
0          AI_Roadmap.txt  engineering         516
1  Annual_Report_2026.txt      finance         479
2       Benefits_2026.txt           hr         610

In [14]:
documents_df["department"].value_counts()

department
engineering    1
finance        1
hr             1
Name: count, dtype: int64

In [15]:
for idx, row in documents_df.iterrows():

    print("=" * 60)

    print(row["filename"])

    print("-" * 60)

    print(row["content"][:200])

============================================================
AI_Roadmap.txt
------------------------------------------------------------

# AI Platform Roadmap

## Search Infrastructure

Vector search infrastructure rollout.

Search latency improved significantly.

New indexing pipeline deployed.

## Retrieval Systems

Hybrid retrieval
============================================================
Annual_Report_2026.txt
------------------------------------------------------------

# Annual Financial Report 2026

## Revenue Performance

Revenue reached $5.2 billion.

Revenue increased across all regions.

Subscription services contributed strongly.

## Profitability

Operating
============================================================
Benefits_2026.txt
------------------------------------------------------------

# Employee Benefits 2026

## Health Insurance

Health insurance coverage increased by 12%.

The company expanded hospitalization benefits.

Employees can now add dependents at reduced rates.

## Dent

In [16]:
repository = {}

for _, row in documents_df.iterrows():

    repository[row["document_id"]] = {
        "filename": row["filename"],
        "department": row["department"],
        "content": row["content"],
    }

In [17]:
first_id = list(repository.keys())[0]

repository[first_id]

{'filename': 'AI_Roadmap.txt',
 'department': 'engineering',
 'content': '\n# AI Platform Roadmap\n\n## Search Infrastructure\n\nVector search infrastructure rollout.\n\nSearch latency improved significantly.\n\nNew indexing pipeline deployed.\n\n## Retrieval Systems\n\nHybrid retrieval implementation.\n\nSemantic search quality improved.\n\nKnowledge base coverage expanded.\n\n## Deployment Roadmap\n\nCross encoder deployment planned.\n\nEnterprise RAG platform launch Q3.\n\nAgentic workflows under evaluation.\n\nComponent | Status\nVector Search | Production\nHybrid Retrieval | Testing\nCross Encoder | Planned\n'}

In [18]:
first_id = list(repository.keys())[0]

repository[first_id]

{'filename': 'AI_Roadmap.txt',
 'department': 'engineering',
 'content': '\n# AI Platform Roadmap\n\n## Search Infrastructure\n\nVector search infrastructure rollout.\n\nSearch latency improved significantly.\n\nNew indexing pipeline deployed.\n\n## Retrieval Systems\n\nHybrid retrieval implementation.\n\nSemantic search quality improved.\n\nKnowledge base coverage expanded.\n\n## Deployment Roadmap\n\nCross encoder deployment planned.\n\nEnterprise RAG platform launch Q3.\n\nAgentic workflows under evaluation.\n\nComponent | Status\nVector Search | Production\nHybrid Retrieval | Testing\nCross Encoder | Planned\n'}

In [19]:
os.makedirs("artifacts", exist_ok=True)

with open("artifacts/document_repository.json", "w", encoding="utf-8") as file:

    json.dump(repository, file, indent=4)

print("Repository saved.")

Repository saved.

In [20]:
repository

{'1fe99400-06e1-4964-956b-3861687e7da4': {'filename': 'AI_Roadmap.txt',
  'department': 'engineering',
  'content': '\n# AI Platform Roadmap\n\n## Search Infrastructure\n\nVector search infrastructure rollout.\n\nSearch latency improved significantly.\n\nNew indexing pipeline deployed.\n\n## Retrieval Systems\n\nHybrid retrieval implementation.\n\nSemantic search quality improved.\n\nKnowledge base coverage expanded.\n\n## Deployment Roadmap\n\nCross encoder deployment planned.\n\nEnterprise RAG platform launch Q3.\n\nAgentic workflows under evaluation.\n\nComponent | Status\nVector Search | Production\nHybrid Retrieval | Testing\nCross Encoder | Planned\n'},
 'b638264b-b788-442e-a09d-19176466fba8': {'filename': 'Annual_Report_2026.txt',
  'department': 'finance',
  'content': '\n# Annual Financial Report 2026\n\n## Revenue Performance\n\nRevenue reached $5.2 billion.\n\nRevenue increased across all regions.\n\nSubscription services contributed strongly.\n\n## Profitability\n\nOperating margin improved to 18%.\n\nCost optimization reduced expenses.\n\nFree cash flow reached record levels.\n\n## Cloud Division\n\nCloud division grew by 35%.\n\nAI products generated record profits.\n\nEnterprise customers expanded usage.\n\nRegion | Revenue\nUS | 2.1B\nEurope | 1.7B\nAsia | 1.4B\n'},
 '31516a79-2cf5-4080-ac66-66b338d6ebff': {'filename': 'Benefits_2026.txt',
  'department': 'hr',
  'content': '\n# Employee Benefits 2026\n\n## Health Insurance\n\nHealth insurance coverage increased by 12%.\n\nThe company expanded hospitalization benefits.\n\nEmployees can now add dependents at reduced rates.\n\n## Dental Benefits\n\nDental insurance remains unchanged.\n\nPreventive dental checkups remain fully covered.\n\nOrthodontic coverage was extended for children.\n\n## Remote Work Policy\n\nRemote work allowance increased.\n\nEmployees may claim internet reimbursement.\n\nWork-from-home equipment support continues.\n\nBenefit | Coverage\nHealth Insurance | 12% Increase\nDental Insurance | No Change\nRemote Work Allowance | Increased\n'}}

In [21]:
documents_df

,document_id,filename,department,doc_type,created_at,content,char_count
0,1fe99400-06e1-4964-956b-3861687e7da4,AI_Roadmap.txt,engineering,corporate_document,2026-01-01,\n# AI Platform Roadmap\n\n## Search Infrastru...,516
1,b638264b-b788-442e-a09d-19176466fba8,Annual_Report_2026.txt,finance,corporate_document,2026-01-01,\n# Annual Financial Report 2026\n\n## Revenue...,479
2,31516a79-2cf5-4080-ac66-66b338d6ebff,Benefits_2026.txt,hr,corporate_document,2026-01-01,\n# Employee Benefits 2026\n\n## Health Insura...,610

In [22]:
documents_df.to_csv("artifacts/document_metadata.csv", index=False)