# 06 Bm25 Retrieval

**Project:** Enterprise Multi-Document RAG Assistant

**Notebook:** `06-bm25-retrieval.ipynb`

In [ ]:
# Start coding here

In [2]:
# =====================================================
# Notebook 06
# BM25 Retrieval
# =====================================================

import pandas as pd

from rank_bm25 import BM25Okapi

In [3]:
children_df = pd.read_csv("artifacts/child_chunks.csv")

children_df.head()

,child_id,parent_id,document_id,content
0,5f2b6fb4-0d03-4817-900a-945162a178c2,7d09d047-2858-43c4-bf8b-d40519129087,1fe99400-06e1-4964-956b-3861687e7da4,AI Platform Roadmap\nSearch Infrastructure\nRe...
1,047bf5df-d450-4bbe-92c2-2396ed3a7b30,7d09d047-2858-43c4-bf8b-d40519129087,1fe99400-06e1-4964-956b-3861687e7da4,ructure rollout.\nSearch latency improved sign...
2,b400d323-ca7c-4813-ac4e-a2ba69786f3f,7d09d047-2858-43c4-bf8b-d40519129087,1fe99400-06e1-4964-956b-3861687e7da4,eval implementation.\nSemantic search quality ...
3,e68fd4e0-8796-416e-b24b-46ccae0f8d1d,a1c5bb38-4de7-4ca4-805a-7e3fc0419867,1fe99400-06e1-4964-956b-3861687e7da4,er deployment planned.\nEnterprise RAG platfor...
4,e001567a-7134-4290-9ebb-e7e07e069dcb,a1c5bb38-4de7-4ca4-805a-7e3fc0419867,1fe99400-06e1-4964-956b-3861687e7da4,ent | Status\nVector Search | Production\nHybr...

In [4]:
children_df.iloc[0]["content"]

'AI Platform Roadmap\nSearch Infrastructure\nRetrieval Systems\nDeployment Roadmap\nVector search infrast'

In [5]:
tokenized_corpus = []

for text in children_df["content"]:

    tokens = text.lower().split()

    tokenized_corpus.append(tokens)

In [6]:
tokenized_corpus[0]

['ai',
 'platform',
 'roadmap',
 'search',
 'infrastructure',
 'retrieval',
 'systems',
 'deployment',
 'roadmap',
 'vector',
 'search',
 'infrast']

In [7]:
bm25 = BM25Okapi(tokenized_corpus)

In [8]:
def bm25_search(query, top_k=5):

    query_tokens = query.lower().split()

    scores = bm25.get_scores(query_tokens)

    results = children_df.copy()

    results["bm25_score"] = scores

    results = results.sort_values(by="bm25_score", ascending=False)

    return results.head(top_k)

In [9]:
bm25_search("health insurance")

,child_id,parent_id,document_id,content,bm25_score
10,94b65479-1416-48a7-ae99-683771424584,fd7bb5e1-9ec6-470a-8726-bbdc04fcc6dc,31516a79-2cf5-4080-ac66-66b338d6ebff,Employee Benefits 2026\nHealth Insurance\nDent...,4.446531
14,bf58e000-ff75-462f-aea5-b36c88ec1f52,4d127151-0af4-4b00-bdad-b66ad91aa656,31516a79-2cf5-4080-ac66-66b338d6ebff,im internet reimbursement.\nWork-from-home equ...,1.824645
12,8ff21095-c362-44d2-b85c-f61357e6e868,fd7bb5e1-9ec6-470a-8726-bbdc04fcc6dc,31516a79-2cf5-4080-ac66-66b338d6ebff,t reduced rates.\nDental insurance remains unc...,1.352840
15,8f9c8a32-8b04-41a2-ae0c-0ca03b1fd491,4d127151-0af4-4b00-bdad-b66ad91aa656,31516a79-2cf5-4080-ac66-66b338d6ebff,urance | 12% Increase\nDental Insurance | No C...,1.307693
0,5f2b6fb4-0d03-4817-900a-945162a178c2,7d09d047-2858-43c4-bf8b-d40519129087,1fe99400-06e1-4964-956b-3861687e7da4,AI Platform Roadmap\nSearch Infrastructure\nRe...,0.000000

In [10]:
bm25_search("revenue")

,child_id,parent_id,document_id,content,bm25_score
5,0b338cc8-85bc-440a-b1a2-a88b6a8b035b,9cb41e2d-b979-4c89-a091-01db42c3748e,b638264b-b788-442e-a09d-19176466fba8,Annual Financial Report 2026\nRevenue Performa...,1.931437
6,fae64b23-bac1-4b0c-8f50-029329796b70,9cb41e2d-b979-4c89-a091-01db42c3748e,b638264b-b788-442e-a09d-19176466fba8,illion.\nRevenue increased across all regions....,1.453179
9,0dcc44dc-097f-463f-b5d4-7e1614ce3ef3,7cdee370-fba0-4bc7-9fe1-a39230162073,b638264b-b788-442e-a09d-19176466fba8,\nRegion | Revenue\nUS | 2.1B\nEurope | 1.7B\n...,1.401215
0,5f2b6fb4-0d03-4817-900a-945162a178c2,7d09d047-2858-43c4-bf8b-d40519129087,1fe99400-06e1-4964-956b-3861687e7da4,AI Platform Roadmap\nSearch Infrastructure\nRe...,0.000000
1,047bf5df-d450-4bbe-92c2-2396ed3a7b30,7d09d047-2858-43c4-bf8b-d40519129087,1fe99400-06e1-4964-956b-3861687e7da4,ructure rollout.\nSearch latency improved sign...,0.000000

In [11]:
queries = ["health insurance", "revenue", "AI platform", "cloud"]

In [12]:
for query in queries:

    print("\n")
    print("=" * 60)

    print("QUERY:", query)

    results = bm25_search(query, top_k=1)

    print(results.iloc[0]["content"])

============================================================
QUERY: health insurance
Employee Benefits 2026
Health Insurance
Dental Benefits
Remote Work Policy
Health insurance coverage


============================================================
QUERY: revenue
Annual Financial Report 2026
Revenue Performance
Profitability
Cloud Division
Revenue reached $5.2 b


============================================================
QUERY: AI platform
AI Platform Roadmap
Search Infrastructure
Retrieval Systems
Deployment Roadmap
Vector search infrast


============================================================
QUERY: cloud
Annual Financial Report 2026
Revenue Performance
Profitability
Cloud Division
Revenue reached $5.2 b

In [13]:
metadata_df = pd.read_csv("artifacts/document_metadata.csv")

In [14]:
children_df = children_df.merge(
    metadata_df[["document_id", "department"]], on="document_id", how="left"
)

In [15]:
department_bm25 = {}

department_docs = {}

In [16]:
for department in children_df["department"].unique():

    subset = children_df[children_df["department"] == department].reset_index(drop=True)

    corpus = [text.lower().split() for text in subset["content"]]

    department_bm25[department] = BM25Okapi(corpus)

    department_docs[department] = subset

In [17]:
department_bm25.keys()

dict_keys(['engineering', 'finance', 'hr'])

In [18]:
def bm25_department_search(query, department, top_k=5):

    bm25_index = department_bm25[department]

    docs = department_docs[department]

    query_tokens = query.lower().split()

    scores = bm25_index.get_scores(query_tokens)

    docs = docs.copy()

    docs["bm25_score"] = scores

    docs = docs.sort_values(by="bm25_score", ascending=False)

    return docs.head(top_k)

In [19]:
bm25_department_search("health insurance", "hr")

,child_id,parent_id,document_id,content,department,bm25_score
0,94b65479-1416-48a7-ae99-683771424584,fd7bb5e1-9ec6-470a-8726-bbdc04fcc6dc,31516a79-2cf5-4080-ac66-66b338d6ebff,Employee Benefits 2026\nHealth Insurance\nDent...,hr,0.846497
4,bf58e000-ff75-462f-aea5-b36c88ec1f52,4d127151-0af4-4b00-bdad-b66ad91aa656,31516a79-2cf5-4080-ac66-66b338d6ebff,im internet reimbursement.\nWork-from-home equ...,hr,0.615483
1,f10bc7b7-4708-4a5a-a8a4-f204a0f1d6c3,fd7bb5e1-9ec6-470a-8726-bbdc04fcc6dc,31516a79-2cf5-4080-ac66-66b338d6ebff,increased by 12%.\nThe company expanded hospi...,hr,0.000000
2,8ff21095-c362-44d2-b85c-f61357e6e868,fd7bb5e1-9ec6-470a-8726-bbdc04fcc6dc,31516a79-2cf5-4080-ac66-66b338d6ebff,t reduced rates.\nDental insurance remains unc...,hr,0.000000
3,7e8d5c48-e126-4842-b655-a83e1465301a,4d127151-0af4-4b00-bdad-b66ad91aa656,31516a79-2cf5-4080-ac66-66b338d6ebff,.\nOrthodontic coverage was extended for child...,hr,0.000000

In [20]:
bm25_department_search("revenue growth", "finance")

,child_id,parent_id,document_id,content,department,bm25_score
0,0b338cc8-85bc-440a-b1a2-a88b6a8b035b,9cb41e2d-b979-4c89-a091-01db42c3748e,b638264b-b788-442e-a09d-19176466fba8,Annual Financial Report 2026\nRevenue Performa...,finance,0.368627
1,fae64b23-bac1-4b0c-8f50-029329796b70,9cb41e2d-b979-4c89-a091-01db42c3748e,b638264b-b788-442e-a09d-19176466fba8,illion.\nRevenue increased across all regions....,finance,0.277232
4,0dcc44dc-097f-463f-b5d4-7e1614ce3ef3,7cdee370-fba0-4bc7-9fe1-a39230162073,b638264b-b788-442e-a09d-19176466fba8,\nRegion | Revenue\nUS | 2.1B\nEurope | 1.7B\n...,finance,0.267292
2,6ff28fa9-a270-4db1-8662-3016c0c17aa9,9cb41e2d-b979-4c89-a091-01db42c3748e,b638264b-b788-442e-a09d-19176466fba8,margin improved to 18%.\nCost optimization red...,finance,0.000000
3,f9c01c39-fe13-43cb-9297-81f5de952cca,7cdee370-fba0-4bc7-9fe1-a39230162073,b638264b-b788-442e-a09d-19176466fba8,oud division grew by 35%.\nAI products generat...,finance,0.000000

In [22]:
def routed_bm25_search(query):

    department, scores = route_query(query)

    results = bm25_department_search(query, department)

    return {"route": department, "results": results}

In [ ]:
routed_bm25_search("employee healthcare coverage")

In [23]:
import pickle

with open("artifacts/bm25_indexes.pkl", "wb") as file:

    pickle.dump(department_bm25, file)