# 01 Golden Dataset Assembly

**Project:** LLMOps Monitoring & Evaluation Platform

**Notebook:** `01-golden-dataset-assembly.ipynb`

In [1]:
# Start coding here
# ============================================
# Notebook 01
# Golden Dataset Assembly
# ============================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [2]:
evaluation_columns = ["question", "contexts", "generated_response", "ground_truth"]

evaluation_columns

['question', 'contexts', 'generated_response', 'ground_truth']

In [3]:
evaluation_data = [
    {
        "question": "What is AWS?",
        "contexts": "AWS stands for Amazon Web Services. It is a cloud computing platform.",
        "generated_response": "AWS is Amazon's cloud platform.",
        "ground_truth": "AWS is Amazon Web Services, a cloud computing platform.",
    },
    {
        "question": "What is Azure?",
        "contexts": "Microsoft Azure is a cloud platform offered by Microsoft.",
        "generated_response": "Azure is Microsoft's cloud service.",
        "ground_truth": "Microsoft Azure is a cloud computing platform offered by Microsoft.",
    },
    {
        "question": "What is Google Cloud?",
        "contexts": "Google Cloud Platform provides cloud computing services.",
        "generated_response": "Google Cloud offers cloud services.",
        "ground_truth": "Google Cloud Platform provides cloud computing services.",
    },
]

In [4]:
evaluation_df = pd.DataFrame(evaluation_data)

evaluation_df

,question,contexts,generated_response,ground_truth
0,What is AWS?,AWS stands for Amazon Web Services. It is a cl...,AWS is Amazon's cloud platform.,"AWS is Amazon Web Services, a cloud computing ..."
1,What is Azure?,Microsoft Azure is a cloud platform offered by...,Azure is Microsoft's cloud service.,Microsoft Azure is a cloud computing platform ...
2,What is Google Cloud?,Google Cloud Platform provides cloud computing...,Google Cloud offers cloud services.,Google Cloud Platform provides cloud computing...

In [5]:
evaluation_df.shape

(3, 4)

In [6]:
def validate_schema(dataframe):

    required_columns = ["question", "contexts", "generated_response", "ground_truth"]

    missing_columns = [col for col in required_columns if col not in dataframe.columns]

    if len(missing_columns) > 0:

        raise ValueError(f"Missing columns: {missing_columns}")

    print("Schema validation passed")

In [7]:
validate_schema(evaluation_df)

Schema validation passed

In [8]:
evaluation_df.isnull().sum()

question              0
contexts              0
generated_response    0
ground_truth          0
dtype: int64

In [9]:
evaluation_df.describe(include="object")

,question,contexts,generated_response,ground_truth
count,3,3,3,3
unique,3,3,3,3
top,What is AWS?,AWS stands for Amazon Web Services. It is a cl...,AWS is Amazon's cloud platform.,"AWS is Amazon Web Services, a cloud computing ..."
freq,1,1,1,1

In [10]:
evaluation_df["question_length"] = evaluation_df["question"].str.len()

In [11]:
evaluation_df["answer_length"] = evaluation_df["ground_truth"].str.len()

In [12]:
evaluation_df[["question_length", "answer_length"]].describe()

       question_length  answer_length
count         3.000000       3.000000
mean         15.666667      59.333333
std           4.725816       6.658328
min          12.000000      55.000000
25%          13.000000      55.500000
50%          14.000000      56.000000
75%          17.500000      61.500000
max          21.000000      67.000000

In [13]:
topics = ["AWS", "Azure", "Google Cloud", "Oracle Cloud", "IBM Cloud"]

In [14]:
synthetic_data = []

for topic in topics:

    synthetic_data.append(
        {
            "question": f"What is {topic}?",
            "contexts": f"{topic} is a cloud platform.",
            "generated_response": f"{topic} provides cloud services.",
            "ground_truth": f"{topic} is a cloud computing platform.",
        }
    )

In [15]:
synthetic_df = pd.DataFrame(synthetic_data)

synthetic_df.head()

,question,contexts,generated_response,ground_truth
0,What is AWS?,AWS is a cloud platform.,AWS provides cloud services.,AWS is a cloud computing platform.
1,What is Azure?,Azure is a cloud platform.,Azure provides cloud services.,Azure is a cloud computing platform.
2,What is Google Cloud?,Google Cloud is a cloud platform.,Google Cloud provides cloud services.,Google Cloud is a cloud computing platform.
3,What is Oracle Cloud?,Oracle Cloud is a cloud platform.,Oracle Cloud provides cloud services.,Oracle Cloud is a cloud computing platform.
4,What is IBM Cloud?,IBM Cloud is a cloud platform.,IBM Cloud provides cloud services.,IBM Cloud is a cloud computing platform.

In [16]:
evaluation_df = pd.concat([evaluation_df, synthetic_df], ignore_index=True)

In [17]:
evaluation_df.shape

(8, 6)

In [18]:
while len(evaluation_df) < 20:

    row = {
        "question": f"Question {len(evaluation_df)}",
        "contexts": "Sample context",
        "generated_response": "Sample generated response",
        "ground_truth": "Sample ground truth",
    }

    evaluation_df = pd.concat([evaluation_df, pd.DataFrame([row])], ignore_index=True)

In [19]:
evaluation_df.shape

(20, 6)

In [20]:
evaluation_df.head()

,question,contexts,generated_response,ground_truth,question_length,answer_length
0,What is AWS?,AWS stands for Amazon Web Services. It is a cl...,AWS is Amazon's cloud platform.,"AWS is Amazon Web Services, a cloud computing ...",12.0,55.0
1,What is Azure?,Microsoft Azure is a cloud platform offered by...,Azure is Microsoft's cloud service.,Microsoft Azure is a cloud computing platform ...,14.0,67.0
2,What is Google Cloud?,Google Cloud Platform provides cloud computing...,Google Cloud offers cloud services.,Google Cloud Platform provides cloud computing...,21.0,56.0
3,What is AWS?,AWS is a cloud platform.,AWS provides cloud services.,AWS is a cloud computing platform.,NaN,NaN
4,What is Azure?,Azure is a cloud platform.,Azure provides cloud services.,Azure is a cloud computing platform.,NaN,NaN

In [21]:
train_df, test_df = train_test_split(evaluation_df, test_size=0.2, random_state=42)

In [22]:
print("Train:", len(train_df))

print("Test:", len(test_df))

Train: 16
Test: 4

In [23]:
train_df

,question,contexts,generated_response,ground_truth,question_length,answer_length
8,Question 8,Sample context,Sample generated response,Sample ground truth,NaN,NaN
5,What is Google Cloud?,Google Cloud is a cloud platform.,Google Cloud provides cloud services.,Google Cloud is a cloud computing platform.,NaN,NaN
11,Question 11,Sample context,Sample generated response,Sample ground truth,NaN,NaN
3,What is AWS?,AWS is a cloud platform.,AWS provides cloud services.,AWS is a cloud computing platform.,NaN,NaN
18,Question 18,Sample context,Sample generated response,Sample ground truth,NaN,NaN
16,Question 16,Sample context,Sample generated response,Sample ground truth,NaN,NaN
13,Question 13,Sample context,Sample generated response,Sample ground truth,NaN,NaN
2,What is Google Cloud?,Google Cloud Platform provides cloud computing...,Google Cloud offers cloud services.,Google Cloud Platform provides cloud computing...,21.0,56.0
9,Question 9,Sample context,Sample generated response,Sample ground truth,NaN,NaN
19,Question 19,Sample context,Sample generated response,Sample ground truth,NaN,NaN
4,What is Azure?,Azure is a cloud platform.,Azure provides cloud services.,Azure is a cloud computing platform.,NaN,NaN
12,Question 12,Sample context,Sample generated response,Sample ground truth,NaN,NaN
7,What is IBM Cloud?,IBM Cloud is a cloud platform.,IBM Cloud provides cloud services.,IBM Cloud is a cloud computing platform.,NaN,NaN
10,Question 10,Sample context,Sample generated response,Sample ground truth,NaN,NaN
14,Question 14,Sample context,Sample generated response,Sample ground truth,NaN,NaN
6,What is Oracle Cloud?,Oracle Cloud is a cloud platform.,Oracle Cloud provides cloud services.,Oracle Cloud is a cloud computing platform.,NaN,NaN

In [24]:
test_df

,question,contexts,generated_response,ground_truth,question_length,answer_length
0,What is AWS?,AWS stands for Amazon Web Services. It is a cl...,AWS is Amazon's cloud platform.,"AWS is Amazon Web Services, a cloud computing ...",12.0,55.0
17,Question 17,Sample context,Sample generated response,Sample ground truth,NaN,NaN
15,Question 15,Sample context,Sample generated response,Sample ground truth,NaN,NaN
1,What is Azure?,Microsoft Azure is a cloud platform offered by...,Azure is Microsoft's cloud service.,Microsoft Azure is a cloud computing platform ...,14.0,67.0

In [25]:
evaluation_df.to_csv("../data/golden_dataset.csv", index=False)

In [26]:
loaded_df = pd.read_csv("../data/golden_dataset.csv")

loaded_df.head()

,question,contexts,generated_response,ground_truth,question_length,answer_length
0,What is AWS?,AWS stands for Amazon Web Services. It is a cl...,AWS is Amazon's cloud platform.,"AWS is Amazon Web Services, a cloud computing ...",12.0,55.0
1,What is Azure?,Microsoft Azure is a cloud platform offered by...,Azure is Microsoft's cloud service.,Microsoft Azure is a cloud computing platform ...,14.0,67.0
2,What is Google Cloud?,Google Cloud Platform provides cloud computing...,Google Cloud offers cloud services.,Google Cloud Platform provides cloud computing...,21.0,56.0
3,What is AWS?,AWS is a cloud platform.,AWS provides cloud services.,AWS is a cloud computing platform.,NaN,NaN
4,What is Azure?,Azure is a cloud platform.,Azure provides cloud services.,Azure is a cloud computing platform.,NaN,NaN

In [27]:
{
    "question": "...",
    "contexts": "...",
    "generated_response": "...",
    "ground_truth": "...",
    "trace_id": "...",
    "timestamp": "...",
    "model": "...",
    "latency_ms": ...,
}

{'question': '...',
 'contexts': '...',
 'generated_response': '...',
 'ground_truth': '...',
 'trace_id': '...',
 'timestamp': '...',
 'model': '...',
 'latency_ms': Ellipsis}

In [ ]:
evaluation_df["model"] = "gpt-4"

evaluation_df["latency_ms"] = np.random.randint(200, 1500, len(evaluation_df))
evaluation_df

,question,contexts,generated_response,ground_truth,question_length,answer_length,model,latency_ms
0,What is AWS?,AWS stands for Amazon Web Services. It is a cl...,AWS is Amazon's cloud platform.,"AWS is Amazon Web Services, a cloud computing ...",12.0,55.0,gpt-4,822
1,What is Azure?,Microsoft Azure is a cloud platform offered by...,Azure is Microsoft's cloud service.,Microsoft Azure is a cloud computing platform ...,14.0,67.0,gpt-4,312
2,What is Google Cloud?,Google Cloud Platform provides cloud computing...,Google Cloud offers cloud services.,Google Cloud Platform provides cloud computing...,21.0,56.0,gpt-4,854
3,What is AWS?,AWS is a cloud platform.,AWS provides cloud services.,AWS is a cloud computing platform.,NaN,NaN,gpt-4,1459
4,What is Azure?,Azure is a cloud platform.,Azure provides cloud services.,Azure is a cloud computing platform.,NaN,NaN,gpt-4,576
5,What is Google Cloud?,Google Cloud is a cloud platform.,Google Cloud provides cloud services.,Google Cloud is a cloud computing platform.,NaN,NaN,gpt-4,1370
6,What is Oracle Cloud?,Oracle Cloud is a cloud platform.,Oracle Cloud provides cloud services.,Oracle Cloud is a cloud computing platform.,NaN,NaN,gpt-4,1319
7,What is IBM Cloud?,IBM Cloud is a cloud platform.,IBM Cloud provides cloud services.,IBM Cloud is a cloud computing platform.,NaN,NaN,gpt-4,259
8,Question 8,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,707
9,Question 9,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,1150
10,Question 10,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,958
11,Question 11,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,641
12,Question 12,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,1388
13,Question 13,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,354
14,Question 14,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,1244
15,Question 15,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,891
16,Question 16,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,1079
17,Question 17,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,1484
18,Question 18,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,314
19,Question 19,Sample context,Sample generated response,Sample ground truth,NaN,NaN,gpt-4,843

In [29]:
def dataset_health_report(df):

    report = {
        "rows": len(df),
        "columns": len(df.columns),
        "null_values": df.isnull().sum().sum(),
        "avg_question_length": round(df["question"].str.len().mean(), 2),
    }

    return report

In [30]:
dataset_health_report(evaluation_df)

{'rows': 20, 'columns': 8, 'null_values': 34, 'avg_question_length': 13.15}