# Financial Data Sandbox

**Project:** Financial Planning & Analysis Intelligence Platform

**Notebook:** `01-financial-data-sandbox.ipynb`

In [33]:
# ==========================================
# Notebook 01
# Financial Data Sandbox
# ==========================================

import pandas as pd
import numpy as np

In [34]:
financial_data = [
    # === YEAR 1: 2023 ===
    {
        "ticker": "ABC",
        "quarter": "2023-Q1",
        "revenue_million": 120,
        "gross_margin_pct": 58,
        "operating_income_million": 22,
        "net_income_million": 16,
        "eps": 1.20,
        "earnings_call": """
        Demand remained strong across enterprise customers.
        We expect continued growth next quarter.
        Supply chain constraints are gradually easing.
        """,
        "risk_factors": """
        Inflation remains a concern.
        Global logistics costs remain elevated.
        """,
        "mda_section": """
        Management believes demand trends remain healthy.
        Customer retention continues to improve.
        """,
    },
    {
        "ticker": "ABC",
        "quarter": "2023-Q2",
        "revenue_million": 128,
        "gross_margin_pct": 60,
        "operating_income_million": 25,
        "net_income_million": 18,
        "eps": 1.35,
        "earnings_call": """
        Enterprise adoption accelerated.
        Pricing pressure has moderated.
        We expect strong momentum in Q3.
        """,
        "risk_factors": """
        Competitive pressure exists.
        Currency fluctuations may impact revenue.
        """,
        "mda_section": """
        New product launches contributed positively.
        Pipeline remains healthy.
        """,
    },
    {
        "ticker": "ABC",
        "quarter": "2023-Q3",
        "revenue_million": 138,
        "gross_margin_pct": 61,
        "operating_income_million": 28,
        "net_income_million": 21,
        "eps": 1.52,
        "earnings_call": """
        Customer demand exceeded expectations.
        Supply chain bottlenecks largely resolved.
        International expansion continues.
        """,
        "risk_factors": """
        Geopolitical uncertainty remains.
        Regulatory changes may affect operations.
        """,
        "mda_section": """
        Strong customer growth across regions.
        Profitability improved significantly.
        """,
    },
    {
        "ticker": "ABC",
        "quarter": "2023-Q4",
        "revenue_million": 150,
        "gross_margin_pct": 63,
        "operating_income_million": 32,
        "net_income_million": 24,
        "eps": 1.72,
        "earnings_call": """
        Record quarter performance.
        Management expects continued growth.
        Demand remains exceptionally strong.
        """,
        "risk_factors": """
        Macroeconomic slowdown remains possible.
        Talent acquisition costs continue rising.
        """,
        "mda_section": """
        Revenue growth exceeded internal expectations.
        Operating leverage improved.
        """,
    },
    # === YEAR 2: 2024 ===
    {
        "ticker": "ABC",
        "quarter": "2024-Q1",
        "revenue_million": 158,
        "gross_margin_pct": 62,
        "operating_income_million": 34,
        "net_income_million": 26,
        "eps": 1.85,
        "earnings_call": """
        Strong start to the fiscal year driven by enterprise renewals.
        Investments in automation are beginning to pay off.
        Seasonality impacted sequential expansion slightly, but YoY trends remain robust.
        """,
        "risk_factors": """
        Increased cyber security threats require higher defensive spend.
        Labor market tightness may impact R&D delivery timelines.
        """,
        "mda_section": """
        Gross margin slightly contracted due to upfront infrastructure investments.
        Operating cash flow remains healthy and aligned with projections.
        """,
    },
    {
        "ticker": "ABC",
        "quarter": "2024-Q2",
        "revenue_million": 167,
        "gross_margin_pct": 64,
        "operating_income_million": 38,
        "net_income_million": 29,
        "eps": 2.05,
        "earnings_call": """
        New AI-driven product modules saw record adoption rates.
        North American markets outperformed our internal forecasts.
        We are raising our full-year guidance based on current pipeline visibility.
        """,
        "risk_factors": """
        Intense competition in the mid-market segment could squeeze pricing.
        Foreign exchange headwinds may create minor revenue drag.
        """,
        "mda_section": """
        Expansion of gross margin driven by favorable product mix shifts.
        Sales and marketing efficiency improved year-over-year.
        """,
    },
    {
        "ticker": "ABC",
        "quarter": "2024-Q3",
        "revenue_million": 174,
        "gross_margin_pct": 64,
        "operating_income_million": 41,
        "net_income_million": 31,
        "eps": 2.18,
        "earnings_call": """
        European expansion is yielding solid initial returns despite local economic headwinds.
        Customer churn hit an all-time low this quarter.
        Strategic partnerships are expanding our addressable market.
        """,
        "risk_factors": """
        Evolving global data privacy laws could increase compliance costs.
        Macroeconomic softening in key European zones poses a growth risk.
        """,
        "mda_section": """
        Operating margin expanded due to scale and cost containment strategies.
        Deferred revenue balances grew substantially, indicating strong future bookings.
        """,
    },
    {
        "ticker": "ABC",
        "quarter": "2024-Q4",
        "revenue_million": 190,
        "gross_margin_pct": 65,
        "operating_income_million": 46,
        "net_income_million": 35,
        "eps": 2.45,
        "earnings_call": """
        An exceptional finish to 2024, crossing historical revenue thresholds.
        Enterprise multi-year deals accelerated significantly in December.
        We enter 2025 with strong fundamental momentum and high visibility.
        """,
        "risk_factors": """
        Potential shifts in corporate tax rates could impact net profitability.
        Heavy reliance on primary cloud infrastructure providers limits operational flexibility.
        """,
        "mda_section": """
        Record annual performance driven by both new customer acquisition and expansion.
        The board has approved an expansion of our share buyback program reflecting capital strength.
        """,
    },
    # === YEAR 3: 2025 ===
    {
        "ticker": "ABC",
        "quarter": "2025-Q1",
        "revenue_million": 198,
        "gross_margin_pct": 64,
        "operating_income_million": 48,
        "net_income_million": 36,
        "eps": 2.52,
        "earnings_call": """
        We carried the strong closing momentum of last year into Q1.
        Professional services revenue saw an unexpected upside.
        Implementation timelines for major cloud migrations have shortened.
        """,
        "risk_factors": """
        Geopolitical trade restrictions could indirectly affect our hardware partners.
        Higher energy and cloud data center costs could pressure margins.
        """,
        "mda_section": """
        Growth continues at a stable pace despite broader macroeconomic caution.
        The balance sheet remains unleveraged with strong liquidity.
        """,
    },
    {
        "ticker": "ABC",
        "quarter": "2025-Q2",
        "revenue_million": 210,
        "gross_margin_pct": 66,
        "operating_income_million": 53,
        "net_income_million": 40,
        "eps": 2.80,
        "earnings_call": """
        Our SaaS migration is officially complete, driving higher recurring revenue.
        Net expansion rate among existing clients remains above 120%.
        Operational efficiences are manifesting across all units.
        """,
        "risk_factors": """
        Slowing down of tech spending in the financial sector might pose headwinds.
        Patent litigation costs could experience a minor uptick.
        """,
        "mda_section": """
        Gross margins hit a record high due to software-heavy delivery streams.
        R&D efficiency gains allowed us to reinvest in market expansion.
        """,
    },
    {
        "ticker": "ABC",
        "quarter": "2025-Q3",
        "revenue_million": 222,
        "gross_margin_pct": 66,
        "operating_income_million": 57,
        "net_income_million": 43,
        "eps": 3.01,
        "earnings_call": """
        APAC region performance exceeded our three-year growth roadmap.
        Enterprise tier clients are increasingly signing up for multi-product bundles.
        We remain comfortable with current consensus expectations.
        """,
        "risk_factors": """
        Volatile global currency markets could create translation headwind effects.
        Wage inflation in emerging tech hubs remains a point of focus.
        """,
        "mda_section": """
        Operating profit increased significantly on a year-over-year basis.
        Working capital cycles optimized, yielding higher operating cash flow.
        """,
    },
    {
        "ticker": "ABC",
        "quarter": "2025-Q4",
        "revenue_million": 240,
        "gross_margin_pct": 67,
        "operating_income_million": 64,
        "net_income_million": 48,
        "eps": 3.35,
        "earnings_call": """
        A monumental year for ABC, closing out 2025 with stellar financial health.
        Our next-gen platform has fully captured the market vanguard.
        Guidance for 2026 will reflect our expanding market share.
        """,
        "risk_factors": """
        Aggressive counter-pricing by legacy competitors entering our niche.
        Integration complexities from upcoming strategic M&A maneuvers.
        """,
        "mda_section": """
        Full year revenue cross-compared to 2023 demonstrates sustained compounding.
        Strong net income margins reflect high operating leverage across the business model.
        """,
    },
]

In [35]:
# financial_data = [
#     {
#         "ticker": "ABC",
#         "quarter": "2023-Q1",
#         "revenue_million": 120,
#         "gross_margin_pct": 58,
#         "operating_income_million": 22,
#         "net_income_million": 16,
#         "eps": 1.20,
#         "earnings_call": """
#         Demand remained strong across enterprise customers.
#         We expect continued growth next quarter.
#         Supply chain constraints are gradually easing.
#         """,
#         "risk_factors": """
#         Inflation remains a concern.
#         Global logistics costs remain elevated.
#         """,
#         "mda_section": """
#         Management believes demand trends remain healthy.
#         Customer retention continues to improve.
#         """,
#     },
#     {
#         "ticker": "ABC",
#         "quarter": "2023-Q2",
#         "revenue_million": 128,
#         "gross_margin_pct": 60,
#         "operating_income_million": 25,
#         "net_income_million": 18,
#         "eps": 1.35,
#         "earnings_call": """
#         Enterprise adoption accelerated.
#         Pricing pressure has moderated.
#         We expect strong momentum in Q3.
#         """,
#         "risk_factors": """
#         Competitive pressure exists.
#         Currency fluctuations may impact revenue.
#         """,
#         "mda_section": """
#         New product launches contributed positively.
#         Pipeline remains healthy.
#         """,
#     },
#     {
#         "ticker": "ABC",
#         "quarter": "2023-Q3",
#         "revenue_million": 138,
#         "gross_margin_pct": 61,
#         "operating_income_million": 28,
#         "net_income_million": 21,
#         "eps": 1.52,
#         "earnings_call": """
#         Customer demand exceeded expectations.
#         Supply chain bottlenecks largely resolved.
#         International expansion continues.
#         """,
#         "risk_factors": """
#         Geopolitical uncertainty remains.
#         Regulatory changes may affect operations.
#         """,
#         "mda_section": """
#         Strong customer growth across regions.
#         Profitability improved significantly.
#         """,
#     },
#     {
#         "ticker": "ABC",
#         "quarter": "2023-Q4",
#         "revenue_million": 150,
#         "gross_margin_pct": 63,
#         "operating_income_million": 32,
#         "net_income_million": 24,
#         "eps": 1.72,
#         "earnings_call": """
#         Record quarter performance.
#         Management expects continued growth.
#         Demand remains exceptionally strong.
#         """,
#         "risk_factors": """
#         Macroeconomic slowdown remains possible.
#         Talent acquisition costs continue rising.
#         """,
#         "mda_section": """
#         Revenue growth exceeded internal expectations.
#         Operating leverage improved.
#         """,
#     },
# ]

In [36]:
financial_df = pd.DataFrame(financial_data)

In [37]:
financial_df

,ticker,quarter,revenue_million,gross_margin_pct,operating_income_million,net_income_million,eps,earnings_call,risk_factors,mda_section
0,ABC,2023-Q1,120,58,22,16,1.20,\n Demand remained strong across enterp...,\n Inflation remains a concern.\n ...,\n Management believes demand trends re...
1,ABC,2023-Q2,128,60,25,18,1.35,\n Enterprise adoption accelerated.\n ...,\n Competitive pressure exists.\n ...,\n New product launches contributed pos...
2,ABC,2023-Q3,138,61,28,21,1.52,\n Customer demand exceeded expectation...,\n Geopolitical uncertainty remains.\n ...,\n Strong customer growth across region...
3,ABC,2023-Q4,150,63,32,24,1.72,\n Record quarter performance.\n ...,\n Macroeconomic slowdown remains possi...,\n Revenue growth exceeded internal exp...
4,ABC,2024-Q1,158,62,34,26,1.85,\n Strong start to the fiscal year driv...,\n Increased cyber security threats req...,\n Gross margin slightly contracted due...
5,ABC,2024-Q2,167,64,38,29,2.05,\n New AI-driven product modules saw re...,\n Intense competition in the mid-marke...,\n Expansion of gross margin driven by ...
6,ABC,2024-Q3,174,64,41,31,2.18,\n European expansion is yielding solid...,\n Evolving global data privacy laws co...,\n Operating margin expanded due to sca...
7,ABC,2024-Q4,190,65,46,35,2.45,"\n An exceptional finish to 2024, cross...",\n Potential shifts in corporate tax ra...,\n Record annual performance driven by ...
8,ABC,2025-Q1,198,64,48,36,2.52,\n We carried the strong closing moment...,\n Geopolitical trade restrictions coul...,\n Growth continues at a stable pace de...
9,ABC,2025-Q2,210,66,53,40,2.80,\n Our SaaS migration is officially com...,\n Slowing down of tech spending in the...,\n Gross margins hit a record high due ...
10,ABC,2025-Q3,222,66,57,43,3.01,\n APAC region performance exceeded our...,\n Volatile global currency markets cou...,\n Operating profit increased significa...
11,ABC,2025-Q4,240,67,64,48,3.35,"\n A monumental year for ABC, closing o...",\n Aggressive counter-pricing by legacy...,\n Full year revenue cross-compared to ...

In [38]:
financial_df.shape

(12, 10)

In [39]:
financial_df[
    [
        "quarter",
        "revenue_million",
        "gross_margin_pct",
        "operating_income_million",
        "net_income_million",
        "eps",
    ]
]

,quarter,revenue_million,gross_margin_pct,operating_income_million,net_income_million,eps
0,2023-Q1,120,58,22,16,1.20
1,2023-Q2,128,60,25,18,1.35
2,2023-Q3,138,61,28,21,1.52
3,2023-Q4,150,63,32,24,1.72
4,2024-Q1,158,62,34,26,1.85
5,2024-Q2,167,64,38,29,2.05
6,2024-Q3,174,64,41,31,2.18
7,2024-Q4,190,65,46,35,2.45
8,2025-Q1,198,64,48,36,2.52
9,2025-Q2,210,66,53,40,2.80
10,2025-Q3,222,66,57,43,3.01
11,2025-Q4,240,67,64,48,3.35

In [40]:
financial_df[["quarter", "revenue_million"]]

    quarter  revenue_million
0   2023-Q1              120
1   2023-Q2              128
2   2023-Q3              138
3   2023-Q4              150
4   2024-Q1              158
5   2024-Q2              167
6   2024-Q3              174
7   2024-Q4              190
8   2025-Q1              198
9   2025-Q2              210
10  2025-Q3              222
11  2025-Q4              240

In [41]:
for quarter, text in zip(financial_df["quarter"], financial_df["earnings_call"]):

    print("=" * 60)

    print(quarter)

    print("=" * 60)

    print(text)

============================================================
2023-Q1
============================================================

        Demand remained strong across enterprise customers.
        We expect continued growth next quarter.
        Supply chain constraints are gradually easing.

============================================================
2023-Q2
============================================================

        Enterprise adoption accelerated.
        Pricing pressure has moderated.
        We expect strong momentum in Q3.

============================================================
2023-Q3
============================================================

        Customer demand exceeded expectations.
        Supply chain bottlenecks largely resolved.
        International expansion continues.

============================================================
2023-Q4
============================================================

        Record quarter performance.
        Management expects continued growth.
        Demand remains exceptionally strong.

============================================================
2024-Q1
============================================================

        Strong start to the fiscal year driven by enterprise renewals.
        Investments in automation are beginning to pay off.
        Seasonality impacted sequential expansion slightly, but YoY trends remain robust.

============================================================
2024-Q2
============================================================

        New AI-driven product modules saw record adoption rates.
        North American markets outperformed our internal forecasts.
        We are raising our full-year guidance based on current pipeline visibility.

============================================================
2024-Q3
============================================================

        European expansion is yielding solid initial returns despite local economic headwinds.
        Customer churn hit an all-time low this quarter.
        Strategic partnerships are expanding our addressable market.

============================================================
2024-Q4
============================================================

        An exceptional finish to 2024, crossing historical revenue thresholds.
        Enterprise multi-year deals accelerated significantly in December.
        We enter 2025 with strong fundamental momentum and high visibility.

============================================================
2025-Q1
============================================================

        We carried the strong closing momentum of last year into Q1.
        Professional services revenue saw an unexpected upside.
        Implementation timelines for major cloud migrations have shortened.

============================================================
2025-Q2
============================================================

        Our SaaS migration is officially complete, driving higher recurring revenue.
        Net expansion rate among existing clients remains above 120%.
        Operational efficiences are manifesting across all units.

============================================================
2025-Q3
============================================================

        APAC region performance exceeded our three-year growth roadmap.
        Enterprise tier clients are increasingly signing up for multi-product bundles.
        We remain comfortable with current consensus expectations.

============================================================
2025-Q4
============================================================

        A monumental year for ABC, closing out 2025 with stellar financial health.
        Our next-gen platform has fully captured the market vanguard.
        Guidance for 2026 will reflect our expanding market share.

In [42]:
for quarter, text in zip(financial_df["quarter"], financial_df["risk_factors"]):

    print("=" * 60)

    print(quarter)

    print("=" * 60)

    print(text)

============================================================
2023-Q1
============================================================

        Inflation remains a concern.
        Global logistics costs remain elevated.

============================================================
2023-Q2
============================================================

        Competitive pressure exists.
        Currency fluctuations may impact revenue.

============================================================
2023-Q3
============================================================

        Geopolitical uncertainty remains.
        Regulatory changes may affect operations.

============================================================
2023-Q4
============================================================

        Macroeconomic slowdown remains possible.
        Talent acquisition costs continue rising.

============================================================
2024-Q1
============================================================

        Increased cyber security threats require higher defensive spend.
        Labor market tightness may impact R&D delivery timelines.

============================================================
2024-Q2
============================================================

        Intense competition in the mid-market segment could squeeze pricing.
        Foreign exchange headwinds may create minor revenue drag.

============================================================
2024-Q3
============================================================

        Evolving global data privacy laws could increase compliance costs.
        Macroeconomic softening in key European zones poses a growth risk.

============================================================
2024-Q4
============================================================

        Potential shifts in corporate tax rates could impact net profitability.
        Heavy reliance on primary cloud infrastructure providers limits operational flexibility.

============================================================
2025-Q1
============================================================

        Geopolitical trade restrictions could indirectly affect our hardware partners.
        Higher energy and cloud data center costs could pressure margins.

============================================================
2025-Q2
============================================================

        Slowing down of tech spending in the financial sector might pose headwinds.
        Patent litigation costs could experience a minor uptick.

============================================================
2025-Q3
============================================================

        Volatile global currency markets could create translation headwind effects.
        Wage inflation in emerging tech hubs remains a point of focus.

============================================================
2025-Q4
============================================================

        Aggressive counter-pricing by legacy competitors entering our niche.
        Integration complexities from upcoming strategic M&A maneuvers.

In [43]:
for quarter, text in zip(financial_df["quarter"], financial_df["mda_section"]):

    print("=" * 60)

    print(quarter)

    print("=" * 60)

    print(text)

============================================================
2023-Q1
============================================================

        Management believes demand trends remain healthy.
        Customer retention continues to improve.

============================================================
2023-Q2
============================================================

        New product launches contributed positively.
        Pipeline remains healthy.

============================================================
2023-Q3
============================================================

        Strong customer growth across regions.
        Profitability improved significantly.

============================================================
2023-Q4
============================================================

        Revenue growth exceeded internal expectations.
        Operating leverage improved.

============================================================
2024-Q1
============================================================

        Gross margin slightly contracted due to upfront infrastructure investments.
        Operating cash flow remains healthy and aligned with projections.

============================================================
2024-Q2
============================================================

        Expansion of gross margin driven by favorable product mix shifts.
        Sales and marketing efficiency improved year-over-year.

============================================================
2024-Q3
============================================================

        Operating margin expanded due to scale and cost containment strategies.
        Deferred revenue balances grew substantially, indicating strong future bookings.

============================================================
2024-Q4
============================================================

        Record annual performance driven by both new customer acquisition and expansion.
        The board has approved an expansion of our share buyback program reflecting capital strength.

============================================================
2025-Q1
============================================================

        Growth continues at a stable pace despite broader macroeconomic caution.
        The balance sheet remains unleveraged with strong liquidity.

============================================================
2025-Q2
============================================================

        Gross margins hit a record high due to software-heavy delivery streams.
        R&D efficiency gains allowed us to reinvest in market expansion.

============================================================
2025-Q3
============================================================

        Operating profit increased significantly on a year-over-year basis.
        Working capital cycles optimized, yielding higher operating cash flow.

============================================================
2025-Q4
============================================================

        Full year revenue cross-compared to 2023 demonstrates sustained compounding.
        Strong net income margins reflect high operating leverage across the business model.

In [44]:
financial_df["combined_text"] = (
    financial_df["earnings_call"]
    + " "
    + financial_df["risk_factors"]
    + " "
    + financial_df["mda_section"]
)

In [45]:
financial_df[["quarter", "combined_text"]]

    quarter                                      combined_text
0   2023-Q1  \n        Demand remained strong across enterp...
1   2023-Q2  \n        Enterprise adoption accelerated.\n  ...
2   2023-Q3  \n        Customer demand exceeded expectation...
3   2023-Q4  \n        Record quarter performance.\n       ...
4   2024-Q1  \n        Strong start to the fiscal year driv...
5   2024-Q2  \n        New AI-driven product modules saw re...
6   2024-Q3  \n        European expansion is yielding solid...
7   2024-Q4  \n        An exceptional finish to 2024, cross...
8   2025-Q1  \n        We carried the strong closing moment...
9   2025-Q2  \n        Our SaaS migration is officially com...
10  2025-Q3  \n        APAC region performance exceeded our...
11  2025-Q4  \n        A monumental year for ABC, closing o...

In [46]:
financial_df.isnull().sum()

ticker                      0
quarter                     0
revenue_million             0
gross_margin_pct            0
operating_income_million    0
net_income_million          0
eps                         0
earnings_call               0
risk_factors                0
mda_section                 0
combined_text               0
dtype: int64

In [47]:
financial_df.to_csv("../data/financial_corporate_dataset.csv", index=False)

In [48]:
saved_df = pd.read_csv("../data/financial_corporate_dataset.csv")

saved_df.head()

,ticker,quarter,revenue_million,gross_margin_pct,operating_income_million,net_income_million,eps,earnings_call,risk_factors,mda_section,combined_text
0,ABC,2023-Q1,120,58,22,16,1.20,\n Demand remained strong across enterp...,\n Inflation remains a concern.\n ...,\n Management believes demand trends re...,\n Demand remained strong across enterp...
1,ABC,2023-Q2,128,60,25,18,1.35,\n Enterprise adoption accelerated.\n ...,\n Competitive pressure exists.\n ...,\n New product launches contributed pos...,\n Enterprise adoption accelerated.\n ...
2,ABC,2023-Q3,138,61,28,21,1.52,\n Customer demand exceeded expectation...,\n Geopolitical uncertainty remains.\n ...,\n Strong customer growth across region...,\n Customer demand exceeded expectation...
3,ABC,2023-Q4,150,63,32,24,1.72,\n Record quarter performance.\n ...,\n Macroeconomic slowdown remains possi...,\n Revenue growth exceeded internal exp...,\n Record quarter performance.\n ...
4,ABC,2024-Q1,158,62,34,26,1.85,\n Strong start to the fiscal year driv...,\n Increased cyber security threats req...,\n Gross margin slightly contracted due...,\n Strong start to the fiscal year driv...