# Financial Document Ingestion

**Project:** Financial Planning & Analysis Intelligence Platform

**Notebook:** `02-financial-document-ingestion.ipynb`

In [1]:
# Start coding here
# ==========================================
# Notebook 02
# Financial Document Ingestion
# ==========================================

import pandas as pd
import numpy as np
import re

import nltk

from nltk.tokenize import sent_tokenize

nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vinna\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [2]:
financial_df = pd.read_csv("../data/financial_corporate_dataset.csv")

financial_df.head()

,ticker,quarter,revenue_million,gross_margin_pct,operating_income_million,net_income_million,eps,earnings_call,risk_factors,mda_section,combined_text
0,ABC,2023-Q1,120,58,22,16,1.20,\n Demand remained strong across enterp...,\n Inflation remains a concern.\n ...,\n Management believes demand trends re...,\n Demand remained strong across enterp...
1,ABC,2023-Q2,128,60,25,18,1.35,\n Enterprise adoption accelerated.\n ...,\n Competitive pressure exists.\n ...,\n New product launches contributed pos...,\n Enterprise adoption accelerated.\n ...
2,ABC,2023-Q3,138,61,28,21,1.52,\n Customer demand exceeded expectation...,\n Geopolitical uncertainty remains.\n ...,\n Strong customer growth across region...,\n Customer demand exceeded expectation...
3,ABC,2023-Q4,150,63,32,24,1.72,\n Record quarter performance.\n ...,\n Macroeconomic slowdown remains possi...,\n Revenue growth exceeded internal exp...,\n Record quarter performance.\n ...
4,ABC,2024-Q1,158,62,34,26,1.85,\n Strong start to the fiscal year driv...,\n Increased cyber security threats req...,\n Gross margin slightly contracted due...,\n Strong start to the fiscal year driv...

In [3]:
financial_df[["quarter", "earnings_call", "risk_factors", "mda_section"]]

,quarter,earnings_call,risk_factors,mda_section
0,2023-Q1,\n Demand remained strong across enterp...,\n Inflation remains a concern.\n ...,\n Management believes demand trends re...
1,2023-Q2,\n Enterprise adoption accelerated.\n ...,\n Competitive pressure exists.\n ...,\n New product launches contributed pos...
2,2023-Q3,\n Customer demand exceeded expectation...,\n Geopolitical uncertainty remains.\n ...,\n Strong customer growth across region...
3,2023-Q4,\n Record quarter performance.\n ...,\n Macroeconomic slowdown remains possi...,\n Revenue growth exceeded internal exp...
4,2024-Q1,\n Strong start to the fiscal year driv...,\n Increased cyber security threats req...,\n Gross margin slightly contracted due...
5,2024-Q2,\n New AI-driven product modules saw re...,\n Intense competition in the mid-marke...,\n Expansion of gross margin driven by ...
6,2024-Q3,\n European expansion is yielding solid...,\n Evolving global data privacy laws co...,\n Operating margin expanded due to sca...
7,2024-Q4,"\n An exceptional finish to 2024, cross...",\n Potential shifts in corporate tax ra...,\n Record annual performance driven by ...
8,2025-Q1,\n We carried the strong closing moment...,\n Geopolitical trade restrictions coul...,\n Growth continues at a stable pace de...
9,2025-Q2,\n Our SaaS migration is officially com...,\n Slowing down of tech spending in the...,\n Gross margins hit a record high due ...
10,2025-Q3,\n APAC region performance exceeded our...,\n Volatile global currency markets cou...,\n Operating profit increased significa...
11,2025-Q4,"\n A monumental year for ABC, closing o...",\n Aggressive counter-pricing by legacy...,\n Full year revenue cross-compared to ...

In [4]:
def clean_financial_text(text):

    text = str(text)

    text = re.sub(r"\s+", " ", text)

    text = re.sub(r"[^a-zA-Z0-9.,%$ ]", "", text)

    text = text.strip()

    return text

In [5]:
sample_text = financial_df.iloc[0]["combined_text"]

clean_financial_text(sample_text)

'Demand remained strong across enterprise customers. We expect continued growth next quarter. Supply chain constraints are gradually easing. Inflation remains a concern. Global logistics costs remain elevated. Management believes demand trends remain healthy. Customer retention continues to improve.'

In [6]:
financial_df["clean_text"] = financial_df["combined_text"].apply(clean_financial_text)

In [7]:
financial_df[["quarter", "clean_text"]]

    quarter                                         clean_text
0   2023-Q1  Demand remained strong across enterprise custo...
1   2023-Q2  Enterprise adoption accelerated. Pricing press...
2   2023-Q3  Customer demand exceeded expectations. Supply ...
3   2023-Q4  Record quarter performance. Management expects...
4   2024-Q1  Strong start to the fiscal year driven by ente...
5   2024-Q2  New AIdriven product modules saw record adopti...
6   2024-Q3  European expansion is yielding solid initial r...
7   2024-Q4  An exceptional finish to 2024, crossing histor...
8   2025-Q1  We carried the strong closing momentum of last...
9   2025-Q2  Our SaaS migration is officially complete, dri...
10  2025-Q3  APAC region performance exceeded our threeyear...
11  2025-Q4  A monumental year for ABC, closing out 2025 wi...

In [8]:
financial_df["character_count"] = financial_df["clean_text"].apply(len)

financial_df[["quarter", "character_count"]]

    quarter  character_count
0   2023-Q1              299
1   2023-Q2              239
2   2023-Q3              269
3   2023-Q4              260
4   2024-Q1              460
5   2024-Q2              436
6   2024-Q3              482
7   2024-Q4              540
8   2025-Q1              463
9   2025-Q2              464
10  2025-Q3              475
11  2025-Q4              486

In [9]:
def sentence_splitter(text):

    return sent_tokenize(text)

In [10]:
sentence_splitter(financial_df.iloc[0]["clean_text"])

['Demand remained strong across enterprise customers.',
 'We expect continued growth next quarter.',
 'Supply chain constraints are gradually easing.',
 'Inflation remains a concern.',
 'Global logistics costs remain elevated.',
 'Management believes demand trends remain healthy.',
 'Customer retention continues to improve.']

In [11]:
financial_df["sentences"] = financial_df["clean_text"].apply(sentence_splitter)

In [12]:
financial_df[["quarter", "sentences"]]

    quarter                                          sentences
0   2023-Q1  [Demand remained strong across enterprise cust...
1   2023-Q2  [Enterprise adoption accelerated., Pricing pre...
2   2023-Q3  [Customer demand exceeded expectations., Suppl...
3   2023-Q4  [Record quarter performance., Management expec...
4   2024-Q1  [Strong start to the fiscal year driven by ent...
5   2024-Q2  [New AIdriven product modules saw record adopt...
6   2024-Q3  [European expansion is yielding solid initial ...
7   2024-Q4  [An exceptional finish to 2024, crossing histo...
8   2025-Q1  [We carried the strong closing momentum of las...
9   2025-Q2  [Our SaaS migration is officially complete, dr...
10  2025-Q3  [APAC region performance exceeded our threeyea...
11  2025-Q4  [A monumental year for ABC, closing out 2025 w...

In [13]:
def create_chunks(text, chunk_size=3):

    sentences = sent_tokenize(text)

    chunks = []

    for i in range(0, len(sentences), chunk_size):

        chunk = " ".join(sentences[i : i + chunk_size])

        chunks.append(chunk)

    return chunks

In [14]:
create_chunks(financial_df.iloc[0]["clean_text"])

['Demand remained strong across enterprise customers. We expect continued growth next quarter. Supply chain constraints are gradually easing.',
 'Inflation remains a concern. Global logistics costs remain elevated. Management believes demand trends remain healthy.',
 'Customer retention continues to improve.']

In [15]:
financial_df["chunks"] = financial_df["clean_text"].apply(create_chunks)

In [16]:
financial_df[["quarter", "chunks"]]

    quarter                                             chunks
0   2023-Q1  [Demand remained strong across enterprise cust...
1   2023-Q2  [Enterprise adoption accelerated. Pricing pres...
2   2023-Q3  [Customer demand exceeded expectations. Supply...
3   2023-Q4  [Record quarter performance. Management expect...
4   2024-Q1  [Strong start to the fiscal year driven by ent...
5   2024-Q2  [New AIdriven product modules saw record adopt...
6   2024-Q3  [European expansion is yielding solid initial ...
7   2024-Q4  [An exceptional finish to 2024, crossing histo...
8   2025-Q1  [We carried the strong closing momentum of las...
9   2025-Q2  [Our SaaS migration is officially complete, dr...
10  2025-Q3  [APAC region performance exceeded our threeyea...
11  2025-Q4  [A monumental year for ABC, closing out 2025 w...

In [17]:
chunk_records = []

for _, row in financial_df.iterrows():

    for idx, chunk in enumerate(row["chunks"]):

        chunk_records.append(
            {
                "ticker": row["ticker"],
                "quarter": row["quarter"],
                "chunk_id": idx,
                "text": chunk,
            }
        )

In [18]:
chunks_df = pd.DataFrame(chunk_records)

In [19]:
chunks_df.head()

  ticker  quarter  chunk_id                                               text
0    ABC  2023-Q1         0  Demand remained strong across enterprise custo...
1    ABC  2023-Q1         1  Inflation remains a concern. Global logistics ...
2    ABC  2023-Q1         2           Customer retention continues to improve.
3    ABC  2023-Q2         0  Enterprise adoption accelerated. Pricing press...
4    ABC  2023-Q2         1  Competitive pressure exists. Currency fluctuat...

In [20]:
chunks_df["text_length"] = chunks_df["text"].apply(len)

In [21]:
chunks_df.head()

,ticker,quarter,chunk_id,text,text_length
0,ABC,2023-Q1,0,Demand remained strong across enterprise custo...,139
1,ABC,2023-Q1,1,Inflation remains a concern. Global logistics ...,118
2,ABC,2023-Q1,2,Customer retention continues to improve.,40
3,ABC,2023-Q2,0,Enterprise adoption accelerated. Pricing press...,97
4,ABC,2023-Q2,1,Competitive pressure exists. Currency fluctuat...,115

In [22]:
chunks_df.describe(include="all")

,ticker,quarter,chunk_id,text,text_length
count,36,36,36.000000,36,36.000000
unique,1,12,NaN,36,NaN
top,ABC,2023-Q1,NaN,Demand remained strong across enterprise custo...,NaN
freq,36,3,NaN,1,NaN
mean,NaN,NaN,1.000000,NaN,134.694444
std,NaN,NaN,0.828079,NaN,66.211272
min,NaN,NaN,0.000000,NaN,25.000000
25%,NaN,NaN,0.000000,NaN,77.500000
50%,NaN,NaN,1.000000,NaN,123.500000
75%,NaN,NaN,2.000000,NaN,196.250000
max,NaN,NaN,2.000000,NaN,241.000000

In [23]:
for i in range(min(5, len(chunks_df))):

    print("=" * 80)

    print(chunks_df.iloc[i]["text"])

================================================================================
Demand remained strong across enterprise customers. We expect continued growth next quarter. Supply chain constraints are gradually easing.
================================================================================
Inflation remains a concern. Global logistics costs remain elevated. Management believes demand trends remain healthy.
================================================================================
Customer retention continues to improve.
================================================================================
Enterprise adoption accelerated. Pricing pressure has moderated. We expect strong momentum in Q3.
================================================================================
Competitive pressure exists. Currency fluctuations may impact revenue. New product launches contributed positively.

In [24]:
financial_df.to_csv("../data/financial_documents_cleaned.csv", index=False)

In [25]:
chunks_df.to_csv("../data/financial_document_chunks.csv", index=False)

In [26]:
saved_chunks = pd.read_csv("../data/financial_document_chunks.csv")

saved_chunks.head()

,ticker,quarter,chunk_id,text,text_length
0,ABC,2023-Q1,0,Demand remained strong across enterprise custo...,139
1,ABC,2023-Q1,1,Inflation remains a concern. Global logistics ...,118
2,ABC,2023-Q1,2,Customer retention continues to improve.,40
3,ABC,2023-Q2,0,Enterprise adoption accelerated. Pricing press...,97
4,ABC,2023-Q2,1,Competitive pressure exists. Currency fluctuat...,115